owncloud/owncloud-design-system

- .drone.yml
:construction: 
Add .drone.yml file to repo (drone:1.0 syntax? )
> drone builds documentation to dist/docs

- src/styles/theme/base.scss
> removed overflow: hidden from html

- src/elements/OcButton.vue
- src/elements/OcCheckbox.vue
- src/main.js
- src/patterns/OcMenu.vue
- src/styles/_owncloud.scss
- src/styles/theme/buttons.scss
> Apply UiKit+ownCloud style to oc-button, oc-checkbox, oc-menu

- src/elements/OcButton.vue
- src/elements/OcCheckbox.vue
- src/elements/OcImage.vue
- src/elements/OcRadio.vue
- src/elements/OcSwitch.vue
- src/elements/OcTextField.vue
- src/elements/OcTextarea.vue
- src/main.js
- src/tokens/border-radius.yml
- src/tokens/font-size.yml
Add missing aria-labels, focus-styles, labels and other things mentioned in #18.
Still not all open points addressed.
> add missing aria-labels and other adjustments

- src/elements/OcFile.vue
- src/elements/OcProgressPie.vue
- src/styles/_owncloud.scss
- src/styles/theme/_variables.scss
- src/styles/theme/oc-checkbox.scss
- src/styles/theme/oc-progress-pie.scss
> Add more base components

- config/docs.config.js
Reverts owncloud/owncloud-design-system#65
> Revert "oc-table-cell, oc-table-group and oc-table-row don't need their own d…"

- src/patterns/OcTopBar.vue
> oc-topbar: initial proposal

- src/patterns/OcAutocomplete.vue
- src/styles/theme/oc-autocomplete.scss
> Introduce oc-autocomplete

- src/elements/OcTabItem.vue
- src/patterns/OcTabs.vue
fixes https://github.com/owncloud/owncloud-design-system/issues/97
minimal implementation, TODOs added inline, can be implemented when necessary
> add tabs and tab-item

- src/elements/OcLoader.vue
- src/styles/_owncloud.scss
- src/styles/theme/oc-loader.scss
- src/templates/Loader-to-Loading.vue
Closes: https://github.com/owncloud/owncloud-design-system/issues/103
> Add OcLoader

- src/elements/OcDialog.vue
- src/templates/Files.vue
Introducing the Oc-Dialog. Instead of filling it with properties like description and input field, i decided to just give a content slot to fill with whatever is needed. I really would appreciate feedback on the slot.
- refs #93
> introduce oc-dialog

- src/elements/_OcAccordionItem.vue
- src/patterns/OcAccordion.vue
> Add accordion item element and accordion pattern

- src/system.js
> No templates go into the built system

- src/elements/OcFile.vue
- src/patterns/OcFileList.vue
- src/templates/Files.vue
> oc-file: use simple binding and fix event handling

- src/elements/OcFile.vue
- src/styles/theme/oc-file.scss
Fixes https://github.com/owncloud/owncloud-design-system/issues/139
> Add the extension dot natively in the template

- src/elements/OcButton.vue
> allow button text via slot

- src/elements/_OcTableRow.vue
- src/patterns/OcAppLayout.vue
- src/templates/Files.vue
initial app layout with optional left and right bar
- used it to add right sidebar in files template
- also needed adding a click event to the table row
> add initial app layout

- src/elements/OcMenuItem.vue
- src/elements/_OcSidebarNavItem.vue
- src/patterns/OcApplicationMenu.vue
- src/patterns/OcMenu.vue
- src/styles/_owncloud.scss
- src/styles/theme/oc-sidebar-nav-item.scss
Fixes https://github.com/owncloud/owncloud-design-system/issues/148
> Fix item text alignment

- src/patterns/OcTopBar.vue
- src/patterns/_OcTopBarItem.vue
- src/patterns/_OcTopBarLogo.vue
- src/styles/_owncloud.scss
- src/styles/theme/oc-icon.scss
- src/styles/theme/oc-topbar.scss
Fixes https://github.com/owncloud/owncloud-design-system/issues/147
> Fix colors in oc-topbar

- src/elements/OcTextInput.vue
Removed type string from oc-text-input value.
Fixes #179
> Removed type string from oc-text-input

- src/patterns/OcUser.vue
first thing I want to reuse in the sharing dialog
> add oc-user

- src/patterns/OcAppSideBar.vue
move  `oc-app-side-bar` from phoenix to design system
> add oc-app-side-bar

- src/elements/OcMenuItem.vue
- src/patterns/OcMenu.vue
Added translation into the menu link
> Added translation

- docs/components/tokens/Icon.vue
- src/elements/OcFile.vue
- src/elements/OcIcon.vue
- src/styles/theme/_variables.scss
- src/styles/theme/oc-icon.scss
- src/tokens/color.yml
Adding colors based on @wuenschedesign layout
> Adding base colors in OC scheme

- src/elements/OcRadio.vue
allow passing in an actual value
needed for https://github.com/owncloud/phoenix/pull/913
> Allow passign in value to ocRadio

- docs/components/Preview.js
- src/pages/Files.vue
this add a button with will render the component in full screen - this helps in designing the component for different screen sizes
> Render a component/template in fullscreen

- src/elements/OcDialog.vue
Added `header` slot to oc-dialog, title is still existing and can be used if header slot is not used.
ref #126
> add header slot to oc-dialog

- src/elements/OcSwitch.vue
Fix https://github.com/owncloud/owncloud-design-system/issues/134 based on https://stackoverflow.com/a/51432277/6795549
> Emit change event when checkbox model changes

- src/patterns/OcUser.vue
makes the oc-user component move the properties below avatar and action buttons
> Move buttons next to avatar

- src/patterns/OcUploadMenu.vue
Created the upload menu component.
Old menu didn't use UIkit. With UIkit it looks a little bit better (still not perfect but I'll return to this to style lit a little bit more) and was hard to orientate in.
> Created upload-menu component

- src/elements/OcBreadcrumb.vue
- src/elements/OcTabItem.vue
- src/elements/_OcSidebarNavHeader.vue
- src/elements/_OcSidebarNavItem.vue
- src/patterns/OcApplicationMenu.vue
Added slots in TabItem, Breadcrumb and SidebarNavItem
> Added slots in TabItem, Breadcrumb and SidebarNavItem

- src/elements/OcButton.vue
that will make it easier to find the buttons for screen-readers and UI tests (what basically is a screen-reader)
> use aria-label in button

- src/elements/OcCheckbox.vue
- src/elements/OcFilterMenuItem.vue
Created a new menu item component for filter menu
By creating own component we don't need to add every time checkboxes to every item and also the item doesn't need to be wrapped in a link.
> Created filterMenuItem component

- src/elements/_OcSidebarNavItem.vue
- src/pages/Files.vue
- src/patterns/OcApplicationMenu.vue
- src/styles/theme/oc-app-menu.scss
- src/styles/theme/oc-sidebar-nav-item.scss
> new application menu design

- src/elements/_OCDropzone.vue
- src/styles/_owncloud.scss
- src/styles/theme/oc-dropzone.scss
## Description
Created a dropzone component for Phoenix. I haven't figured out a nice way to create an example (because of the fixed position) so, for now, I created it as a hidden component.
> Created oc-dropzone component

- src/patterns/OcFileActions.vue
- src/styles/_owncloud.scss
- src/styles/theme/oc-file-actions.scss
Created oc-file-actions class and moved styles from the components into it and changed colour of actions bar. It's still not perfect colour but I would say it's the most appropriate for that bar from what we have in design tokens. Also it's just temporary so as long as it makes the links a little bit more visible I think it's fine for the time being.
> Created oc-file-actions class and changed colour of actions bar

- src/elements/OCAvatar.vue
- src/pages/Files.vue
Added spinner when avatar is being loaded and placeholder if the src string is empty. Also added flexbox for fixing the alignment for the placeholder.
Fixes: #258 and https://github.com/owncloud/phoenix/issues/971
> Added placeholder and spinner when loading

- src/elements/OcButton.vue
- src/elements/OcGrid.vue
- src/pages/Files.vue
- src/patterns/OcSearchBar.vue
- src/styles/theme/oc-button.scss
- src/styles/theme/oc-search.scss
This is a good basis for laying out apps, but also helps with any other element such as the app-bar.
TODO:
> Add oc-grid element

- src/elements/OCDrop.vue
- src/elements/OcButton.vue
- src/elements/OcTabItem.vue
- src/elements/_OcAccordionItem.vue
- src/elements/_OcSidebarNavDivider.vue
- src/elements/_OcSidebarNavHeader.vue
- src/elements/_OcSidebarNavItem.vue
- src/pages/Files.vue
- src/pages/Login.vue
- src/patterns/OcAccordion.vue
- src/patterns/OcAppLayout.vue
- src/patterns/OcApplicationMenu.vue
- src/patterns/OcFileActions.vue
- src/patterns/_OcTopBarItem.vue
Added slots instead of text props.
- Fixes #200
> Added slots

- src/elements/OCNotificationMessage.vue
- src/elements/OCNotifications.vue
With added message we can display also error message and not only title (or don't have to put it together).
> Added message to notifications and moved texts to slots

- src/elements/OCNotificationMessage.vue
By adding class we can make an easier reference in tests and separate the title and the error description - https://github.com/owncloud/phoenix/pull/1086
> Added class to notification title

- src/elements/OcSwitch.vue
Changed value of checked to model to prevent having default value always false and adjusted documentation to effect the star when switch change is triggered.
> Fixed value and documentation

- src/elements/OcBreadcrumb.vue
- src/pages/Files.vue
Adds an optional first item styled with the home icon.
> Add optional home-item in breadcrumb

- src/pages/Files.vue
- src/patterns/OcAppBar.vue
- Adds a wrapper around the ocGrid component to allow proxy styles.
> Add OcAppBar Component wrapper

- src/elements/OcFile.vue
- src/styles/theme/login.scss
- src/styles/theme/oc-file.scss
- src/styles/theme/oc-search.scss
- src/styles/theme/oc-topbar.scss
fixes #316 
fixes #313 
fixes #315
fixes #314
> IE11 support

- src/styles/theme/oc-topbar.scss
Fixes https://github.com/owncloud/owncloud-design-system/issues/314
> Center topBar personal button

- src/styles/_owncloud.scss
- src/styles/theme/main.scss
- src/styles/theme/oc-app-bar.scss
- src/styles/theme/oc-app-container.scss
- src/styles/theme/oc-scroll.scss
* Add padding and background to app-bar
Only works in conjunction with https://github.com/owncloud/phoenix/pull/1221
> New App-Bar

- src/styles/_owncloud.scss
- src/styles/theme/helper.scss
As per request: https://github.com/owncloud/owncloud-design-system/issues/352
Add first helper CSS class `.oc-cursor-pointer`
> Add cursor helper class

- src/styles/theme/helper.scss
Uikit is missing this pretty simple and yet effective feature.
> Added helper class align-self-center

- src/patterns/OcAutocomplete.vue
- src/styles/theme/oc-autocomplete.scss
- Clicking "x more" expands the autocomplete items list
Fixes: https://github.com/owncloud/smb_acl_frontend/issues/76
To Do:
> Expand autocomplete list

- src/elements/OcButton.vue
- src/styles/theme/oc-button.scss
User needs to be aware that some buttons lead to destructive actions.
- Fixes #391
> Danger variation for button

- src/elements/OCNotificationMessage.vue
Changed element of close icon in alerts to link to enable calling a click on it from methods and added class for better reference in tests.
> Changed alert close icon element to link

- src/patterns/OcAutocomplete.vue
- src/styles/theme/oc-autocomplete.scss
> Change colour of text-meta on hover to inverted

- src/elements/OcCheckbox.vue
related to #415 - not really fixing it - just to make it work as needed in phoenix as of now
> oc-checkbox: stop event propagation of the click event

- src/elements/OCDrop.vue
- src/styles/theme/oc-autocomplete.scss
Added close on click method and prop to drop component.
We can now use drop for select without the need to create its own component.
> Allow closing of drop on click

- src/elements/OCNotificationMessage.vue
- src/elements/OCNotifications.vue
- src/styles/theme/oc-alert.scss
Added transition to messages. Now are animated opacity and change of position in case some message gets closed.
> Added transition to messages

- src/styles/theme/oc-switch.scss
Added different colour to switch off state to make it better distinguishable.
> Fixed off state of switch

- src/elements/OCAvatar.vue
- src/styles/theme/oc-avatar.scss
Stripped avatar component from functionality, made oc-img a root node and changed border-radius.
> Reworked avatar

- src/styles/theme/oc-autocomplete.scss
> Added inverted color to icon in autocomplete

- src/styles/_owncloud.scss
- src/styles/theme/margin.scss
- src/tokens/margins.yml
UIkit provides the small margin as the smallest class. In some cases this is not enough and xsmall margin is needed.
> Added xsmall margin

- src/styles/_owncloud.scss
- src/styles/theme/_oc-page-title.scss
For [phoenix #2162](https://github.com/owncloud/phoenix/pull/2162)
> Establishes .oc-page-title class

- src/patterns/OcSearchBar.vue
Added clear event to a search bar.
- refs https://github.com/owncloud/phoenix/issues/2120
> Search bar clear event

- src/elements/OcButton.vue
As suggested by @michaelstingl a first sketch of an accessibility section in a component.
> Scaffold accessibility documentation for OcButton component

- src/patterns/OcAppSideBar.vue
Fixes in part https://github.com/owncloud/phoenix/issues/1650
> Make close button aria-label configurable, for phoenix #1650

- src/styles/_owncloud.scss
- src/styles/theme/_variables.scss
- src/styles/theme/background.scss
- src/tokens/color.yml
Implemented selected background colour. The value of this colour is taken from Figma oC library colours.
> Introduced selected background colour

- docs/utilities.md
- src/styles/theme/helper.scss
Introduced border utility class. Now it's possible to add a border to any element with class `oc-border`.
> Added border utility class

- src/patterns/OcAppSideBar.vue
- src/patterns/OcAutocomplete.vue
Fixes #548 
@PVince81 This were all hard coded texts I could find.
> Add props for missing translations

- config/docs.config.js
- docs/guidelines.md
- docs/use-of-aria.md
Results of the workshop, destilled in Interface Guidelines documentation page
> Add interface guidelines, for #537

- src/elements/OcDialog.vue
- src/elements/OcTextInput.vue
- src/pages/Files.vue
- src/patterns/OcAccordion.vue
- src/patterns/OcSearchBar.vue
Follow up from https://github.com/owncloud/owncloud-design-system/pull/524
Adjusts all other occurrences from oc-input-field
> Search bar label

- package.json
- src/elements/OCAvatar.vue
- yarn.lock
> Fixes #582 - using vue-avatar

- src/elements/OcIcon.vue
Will be useful for share indicators: #607
> Add small icon size option

- src/elements/OcIcon.vue
- Fix default icon size (regression)
- Fix eslint issues
- Add examples for all variations
> Fix default icon size and add more examples

- changelog/unreleased/583
- src/patterns/OcApplicationMenu.vue
- src/styles/theme/oc-app-menu.scss
> Small sidebar navigation design improvements

- changelog/unreleased/668
- src/patterns/OcApplicationMenu.vue
> Remove width class from sidebar menu

- changelog/unreleased/706-1
- changelog/unreleased/706-2
- src/elements/OcTextInput.vue
- src/patterns/OcSearchBar.vue
- src/styles/theme/oc-search.scss
> Fixed search bar layout

- changelog/unreleased/extended-modal-with-input
- src/elements/OcModal.spec.js
- src/elements/OcModal.vue
- src/elements/__snapshots__/OcModal.spec.js.snap
- src/styles/theme/oc-modal.scss
Input via slot has not been sufficient.
> Extended modal with an input

- changelog/unreleased/sidebar-main-content copy
- src/assets/icons/folder-move.svg
Icon is taken from https://iconify.design/icon-sets/mdi/folder-move.html
> Add move icon

- changelog/unreleased/add-visibility-off-icon
Icon source - https://material.io/resources/icons/?search=eye&icon=visibility_off&style=baseline
> Add visibility off icon

- changelog/unreleased/flat-loader
- src/elements/OcLoader.vue
- src/styles/theme/oc-loader.scss
> Add flat style for oc-loader component

- changelog/unreleased/input-background
- src/styles/theme/oc-text-input.scss
We've moved definition of the input background color from hook into its class.
> Fix input background color

- changelog/unreleased/icon-variation-fix
- src/elements/OCNotificationMessage.vue
Fixes https://github.com/owncloud/owncloud-design-system/issues/843
> Fix variation of icons in notification message

- changelog/unreleased/disabled-buttons-style
- src/elements/OcButton.vue
- src/styles/theme/oc-button.scss
- src/tokens/color.yml
> Change colors of disabled buttons

- changelog/unreleased/tag-component
- src/elements/OcTag.spec.js
- src/elements/OcTag.vue
- src/elements/__snapshots__/OcTag.spec.js.snap
- src/styles/_owncloud.scss
- src/styles/theme/oc-tag.scss
> Add tag component

- changelog/unreleased/breadcrumb-icon-floating
- src/components/OcBreadcrumb.vue
fix: https://github.com/owncloud/ocis/issues/1053
> fix non floating home icon in breadcrumb

- changelog/unreleased/table-footer
- src/components/table/OcTable.vue
- src/components/table/OcTableFiles.vue
- src/components/table/__snapshots__/OcTable.spec.js.snap
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
We've added a footer to the table and table files components. To add any content to the footer, use `footer` slot.
> Add table footer

- changelog/unreleased/add-link-avatar
- src/components/avatars/OcAvatarGroup.vue
- src/components/avatars/OcAvatarLink.vue
- src/components/avatars/__snapshots__/OcAvatarGroup.spec.js.snap
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
We've created a link avatar component which mimics styles of the avatar component.
> Add link avatar component

- changelog/unreleased/improve_image_user_docs
- src/components/OcDatepicker.vue
- src/components/OcImage.vue
- src/components/OcUser.vue
Went for more semantic HTML that also looks slightly better :)
> Quickwin: Improve image & user component documentation

- changelog/unreleased/enhancement-remove-filetype-icon
- docs/components/tokens/Icon.vue
- src/components/OcIcon.vue
- src/components/resource/OcResource.vue
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
- src/styles/theme/oc-icon.scss
- src/tokens/color.yml
Discussed with @kulmann last week, part of refactoring/cleaning up the design system (incl. theming & tokenization)
> Remove filetype icon, update references & docs

- changelog/unreleased/bugfix-datepicker-z-index
- src/components/OcDatepicker.vue
- src/styles/theme/oc-datepicker.scss
> Increase datepicker z-index

- changelog/unreleased/enhancement-add-label-and-messages-to-datepicker
- src/components/OcDatepicker.vue
- src/styles/theme/oc-datepicker.scss
* Remove placeholders
* Add required label to datepickers
* Add optional description message to datepickers
* Add aria-describedby which references the description
* Add aria-invalid property (which is basically always false as the datepicker does not allow invalid inputs -> no errors)
> Implement label and description for the datepicker component

- changelog/unreleased/enhancement-remove-octextinput-component-from-searchbar
- src/components/OcSearchBar.vue
- src/styles/theme/oc-search.scss
Also replace the loading spinner with the OcSpinner component in the course of this.
Related to https://github.com/owncloud/owncloud-design-system/pull/1141 as this PR removes placeholders from the `OcTextInput` component.
> Remove the OcTextInput component from the OcSearchBar component

- changelog/unreleased/enhancement-checkbox-accessibility
- src/components/OcCheckbox.vue
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Add **id** and **for** properties to label
Add **aria-checked**, **aria-labelledby,**  **aria-disabled** property to input
> Added acessibility to checkbox component

- src/components/OcAccordion.vue
Removed by https://github.com/owncloud/owncloud-design-system/pull/1141
> Reintroduce input hint removed by pr #1141

- changelog/unreleased/enhancement-accordion-focus
- src/components/OcAccordion.vue
- src/components/OcAccordionItem.vue
Part of the changes which are required to make sharing a11y compliant: https://jira.owncloud.com/browse/WEB-159
> Add focus border to accordion items

- Makefile
- l10n/.tx/config
- l10n/Makefile
fix l10n make steps and get them working again
> fix l10n make steps

- changelog/unreleased/enhancement-searchbar-accessibility
- src/components/OcSearchBar.vue
- src/styles/theme/oc-search.scss
fixes https://github.com/owncloud/owncloud-design-system/issues/1160
> Make searchbar component a11y-compliant

- changelog/unreleased/enhancement-datepicker-input-style
- src/styles/theme/oc-datepicker.scss
Another very quick win as I don't know when the "new datepicker" will be finished.
> Match datepicker input style with other existing inputs

- changelog/unreleased/dropzone-color
- src/components/OcDropzone.vue
> Use primary text color in dropzone

- changelog/unreleased/enhancement-vue-select
- package.json
- src/components/OcSelect.vue
- yarn.lock
I am on purpose not implementing any unit tests as the lib has its own unit tests and we do not do any custom magic on top of that. Even our test coverage is 100 for that file...
> Add vue select

- changelog/unreleased/bugfix-fixed-logo-width
- src/styles/theme/login.scss
> Remove fixed width for login-logo

- changelog/unreleased/enhancement-table-sorting
- src/components/table/OcTable.sort.spec.js
- src/components/table/OcTable.vue
- src/components/table/OcTableFiles.vue
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
- src/components/table/helpers/constants.js
- src/components/table/mixins/sort.js
- src/components/table/mixins/sort.scss
This PR brings back sorting to the OCTable and OCTableFiles, it also fixes some tests which errored in the before.
> OCTable and OCTableFiles sorting

- src/components/OcAutocomplete.vue
- src/components/OcDropzone.vue
- src/components/OcTag.vue
- src/components/table/OcTable.vue
- src/styles/theme/oc-card.scss
- src/styles/theme/oc-datepicker.scss
- src/styles/theme/oc-file-actions.scss
- src/styles/theme/oc-modal.scss
- src/tokens/ods/color.json
revert background color variable
> revert background color

- changelog/unreleased/change-sidebar-a11y
- src/components/OcSidebar.vue
- src/components/OcSidebarNavItem.vue
* Added a current page indicator to the sidebar.
* Added an overall aria label to the sidebar
* Added an alt property for the logo. It used the product name previously which is problematic because alt needs to describe the link rather than the image.
* Remove unnecessary prefixes from property- and method-names
> Accessibility improvements on the sidebar component

- changelog/unreleased/bugfix-unnecessary-icon-role
- changelog/unreleased/enhancement-accordion-accessibility
- src/components/OcAccordion.vue
- src/components/OcAccordionItem.vue
- src/components/OcIcon.vue
- src/components/OcSidebar.spec.js
- src/components/__snapshots__/OcSidebar.spec.js.snap
- src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Small a11y changes regarding the oc-icon and oc-accordion components.
> A11y improvements

- changelog/unreleased/enhancement-tooltips
- src/components/resource/OcResourceName.spec.js
- src/components/resource/OcResourceName.vue
- src/components/resource/__snapshots__/OcResourceName.spec.js.snap
> Change ResourceName tooltip from uikit to v-oc-tooltip

- changelog/unreleased/enhancement-avatar-link-count-a11y
- src/components/avatars/OcAvatarCount.vue
- src/components/avatars/OcAvatarLink.vue
- src/components/avatars/__snapshots__/OcAvatarCount.spec.js.snap
> A11y improvements in avatar link & avatar count

- docs/docs.styles.scss
- src/components/OCNotifications.vue
- src/components/OcAppSideBar.vue
- src/components/OcAutocomplete.vue
- src/components/OcButton.vue
- src/components/OcCheckbox.vue
- src/components/OcDatepicker.vue
- src/components/OcGrid.vue
- src/components/OcHiddenAnnouncer.vue
- src/components/OcIcon.vue
- src/components/OcLoader.vue
- src/components/OcProgressPie.vue
- src/components/OcRadio.vue
- src/components/OcSearchBar.vue
- src/components/OcSelect.vue
- src/components/OcTextInput.vue
- src/components/OcTextarea.vue
- src/components/OcUser.vue
- src/components/resource/OcResourceSize.vue
- src/components/table/OcTable.vue
- src/components/table/OcTableSimple.vue
- src/styles/theme/oc-text.scss
No changelog item since it (basically) only touches examples
> Internalize some uikit classes to OC

- .github/issue_template.md
- .github/pull_request_template.md
- .github/settings.yml
> Update repo description, add issue & PR templates

- package.json
- src/components/OcStatusIndicators.vue
- src/components/avatars/OcAvatar.vue
- src/components/resource/OcResourceName.spec.js
- src/components/resource/OcResourceName.vue
- src/components/resource/__snapshots__/OcResourceName.spec.js.snap
This PR introduces attributes that serve testing purposes. For now they'll land in the production html.
Test resilience
> Introduce dedicated `data-test` attributes for e2e tests

- src/components/avatars/OcAvatarGroup.vue
- src/components/avatars/__snapshots__/OcAvatarGroup.spec.js.snap
Forgot to add this in the former PR 🥴
> Use displayName in AvatarGroup

- package.json
> Prepare 7.1.2 release

- src/components/avatars/OcAvatarLink.vue
This PR adds a test attribute containing the name of the link to the `OcAvatarLink` component.
Test resilience.
> Add test attribute for link name to OcAvatarLink

- .drone.star
- sonar-project.properties
With this PR:
- Add sonarcloud scanner to owncloud design system
Related issue:
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1365
> [tests-only] added solar configurations for unit tests

- src/styles/theme/background.scss
> fix: use correct highlight colour

- .eslintignore
- docs/utils/activeNav.spec.js
- docs/utils/filterSearch.spec.js
- docs/utils/statusLabels.spec.js
- src/components/OcBreadcrumb.spec.js
- src/components/OcDrop.spec.js
- src/components/OcModal.spec.js
- src/components/OcProgress.spec.js
- src/components/OcSidebarNav.spec.js
- src/components/OcTag.spec.js
- src/components/avatars/OcAvatarGroup.spec.js
- src/components/pagination/OcPagination.spec.js
- src/components/resource/OcResource.spec.js
- src/components/resource/OcResourceSize.spec.js
- src/components/table/OcTable.sort.spec.js
- src/components/table/OcTableCell.spec.js
- src/components/table/OcTableFiles.spec.js
- src/system.spec.js
- unskip test spec files from linting
- 🤖
> Enable lint for test spec files

- src/components/OcAccordion.spec.js
added unit tests for accordion component
- 🤖
> [tests-only] added unit tests for accordion component

- README.md
show current coverage
part of https://github.com/owncloud/web/issues/5217
see progress
> [tests-only] add coverage badge

- changelog/unreleased/bugfix-visible-separator-sidebarnav-items
- src/components/OcSidebarNavItem.vue
See changelog item and issue
- Fixes #1387
> Add separator between OcSidebarNav items

- changelog/unreleased/bugfix-remove-pagination-list-padding
- src/components/pagination/OcPagination.vue
Internalized from `web` master
> Remove pagination list padding

- changelog/unreleased/bugfix-half-pixel-border-sidebarnav
- src/components/OcSidebarNavItem.vue
> Fix SidebarNav item border

- .drone.star
Break the testing pipeline step into lint, build and testing pipelines so that the CI can fail faster.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1357
:robot:
> [ci] rearrange ci steps to optimize runtime

- .drone.star
Reverts owncloud/owncloud-design-system#1415
> Revert "[ci] rearrange ci steps to optimize runtime"

- .drone.star
Run the unit tests before build step in CI as it takes less time than build and we can get failed build quicker if unit tests fail.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1357
> [ci] Run unit tests before build in CI

- src/components/avatars/OcAvatar.spec.js
- src/components/avatars/OcAvatar.vue
With this PR: 
- unit tests for `OcAvatar` component are added
- part of #1366 
- increase unit test coverage
- 🤖
> [tests-only] added unit test for oc avatar component

- src/components/OcCheckbox.spec.js
Added following unit tests for OcCheckbox component describing
- input id
- input label
- input size
- set checked
- increase unit tests coverage
- 🤖
> Added unit tests for oc checkbox component

- src/components/avatars/OcAvatar.spec.js
- do not expect for default style value
https://github.com/owncloud/owncloud-design-system/pull/1424#discussion_r658660121
- 🤖
> Removed test for default style value

- jest.conf.js
- jest.overrides.js
- src/components/OcButton.spec.js
- there are some errors that should be caught but sneaked by VueJs. `[Vue Warn]` warning is one of them
- global console contains these error from where we can assert if they are expected errors or else fail the tests 
- 💇🏼‍♂️ 
- 🤖
> [tests-only] fail test if console error contains Vue warn

- changelog/unreleased/change-previews-to-thumbnails
- src/components/resource/OcResource.spec.js
- src/components/resource/OcResource.vue
- src/components/table/OcTableFiles.spec.js
- src/components/table/OcTableFiles.vue
> Rename previews => thumbnails in OcResource & OcTableFiles

- docs/versioning-and-release.md
> Add hint for sonarcloud & transifex to release guide

- src/components/OcActionDrop.spec.js
- src/components/OcActionDrop.vue
Added following uni tests:
- toggle dropdown
- when toggle button is toggled
- when dropdown is open and  menu is clicked
- open menu and focus
- 🤖
> Added unit tests for OcActionDrop

- src/components/avatars/OcAvatarLink.spec.js
- unit test coverage
- 🤖 
- 👨🏼‍🎨
> added unit tests for oc avatar link component

- src/components/OcDropzone.spec.js
added unit  tests for `OcDropzone` component
- unit test coverage
- 🤖
> added unit tests for oc dropzone component

- src/components/OcGrid.spec.js
With this PR:
- added unit tests for `OcGird` component
- 🐓
> added unit tests for OcGrid component

- src/components/OcImage.spec.js
added unit tests for `OcImage` component
- 🤖
> added unit tests for OcImage component

- src/components/OcHiddenAnnouncer.spec.js
- src/components/OcHiddenAnnouncer.vue
- added unit tests for `OcHiddenAnnouncer` component
- Fixes #1366 
- 🤖
> added unit tests for OcHiddenAnnouncer component

- .drone.star
start the build steps only after unit tests have succeded
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1357
to get quicker feedback on PRs
🤖
> [CI] start the build steps only after unit tests have succeded

- src/components/OcNavbarItem.spec.js
added unit test for `_OcNavbarItem` component
- 🤖
> Added unit tests for _OcNavbarItem component

- src/components/OcNavbar.spec.js
- src/components/OcNavbar.vue
added unit tests for `OcNavbar` component
- 👦🏼 
- 🤖
> added unit tests for OcNavbar component

- src/components/OcStatusIndicators.vue
- src/components/switch/OcSwitch.spec.js
- src/components/switch/OcSwitch.vue
See https://github.com/owncloud/web/discussions/5367
> Switch from data-test-id to data-testid

- src/components/OcLoader.spec.js
Added unit tests for `OcLoader` component
- 🤖
> Added unit tests for OcLoader component

- src/components/OcLogo.spec.js
- added unit tests of `OcLogo` component
- Fixes #1366 
- 🤖
> Added unit tests for OcLogo component

- src/components/OcAccordionItem.spec.js
- src/components/OcAccordionItem.vue
- added import for components used inside
> testing without import fills console with vue warn errors, see details ⬇️ 
<details>
```console
[Vue warn]: Unknown custom element: <oc-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <OcAccordionItem>
<Root>
at warn (node_modules/vue/dist/vue.runtime.common.dev.js:621:15)
at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5918:11)
at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6033:9)
at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5934:9)
at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6033:9)
at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5934:9)
at VueComponent.patch [as __patch__] …
```
> [tests-only] added unit tests for accordion item

- src/components/OcNav.spec.js
- added unit tests for `OcNav` component
- 🤖
> [unit-tests] added unit tests for OcNav component

- src/assets/icons/feedback.svg
Add `feedback` icon to icon assets
Coming from google material design. License is apache 2.0, so no attribution is required.
https://fonts.google.com/icons?selected=Material+Icons:feedback
> Add `feedback` icon

- src/components/OcNavItem.spec.js
- src/components/OcNavItem.vue
Added unit tests for `OcNavItem` component
- 👨🏼‍🎨 
- 🤖
> [unit-tests] added unit tests for OcNavItem item component

- src/components/OcRadio.spec.js
Added unit tests for `OcRadio` component
- 👨🏼‍🎨 
- 🤖
> [unit-tests] Added unit tests for OcRadio component

- changelog/unreleased/change-remove-select-model
- changelog/unreleased/enhancement-add-page-size
- src/components/OcSelect.vue
- src/components/page-size/OcPageSize.spec.js
- src/components/page-size/OcPageSize.vue
- src/tokens/ods/size.yaml
> feat: add page size component

- src/components/OcSearchBar.spec.js
- src/components/OcSearchBar.vue
- Added unit tests for `OcSearchBar` component
- 💇🏼‍♂️ 
- 🤖 
- [ x Tests
- [ x] Unit tests added
> [unit-tests] added unit tests for OcSearchBar component

- src/components/OcTextInput.spec.js
- added unit tests for `OcTextInput` component
- 💇🏼‍♂️ 
- 🤖
> [unit-tests] Added more unit tests for OcTextInput component

- changelog/unreleased/bugfix-inverse-button-hover
- src/components/OcButton.vue
> Fix inverse OcButton icon hover issue

- src/components/OcNotificationMessage.spec.js
- src/components/OcNotificationMessage.vue
Added unit tests for `OcNotificationMessage` component
- 👨🏼‍🎨 
- 🤖
> [unit-tests] added unit tests for OcNotificationMessage component

- changelog/unreleased/bugfix-ocswitch-off-state-is-not-pixel-perfect
- src/components/switch/OcSwitch.vue
See changelog item
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1458
> Bugfix: OcSwitch off state is not pixel-perfect

- src/components/OcUser.spec.js
- src/components/OcUser.vue
Added unit tests for `OcUser` component
- unit tests coverage
- 🤖
> [unit-tests] Added unit tests for OcUser component

- changelog/unreleased/enhancement-ocswitch-state-color-difference
- src/components/switch/OcSwitch.vue
See #1457 
- Fixes #1457 
See changelog
> #1457 Ocswitch off state color

- src/components/OcRecipient/OcRecipient.vue
> Update OcRecipient component release info

- changelog/unreleased/enhancement-sign-out-icon
- src/assets/icons/sign-out.svg
Works towards https://github.com/owncloud/web/issues/5590
> Add dedicated sign-out icon

- changelog/unreleased/bugfix-selected-files-drag-drop
- src/components/table/OcTableFiles.vue
We used a local prop to hold the state of the selection model of octablefiles which turned out to be wrong.
Should be fixed with this PR.
> Bugfix: OcTableFiles selection model

- changelog/unreleased/enhancement-add-sidebar-toggle-icons
- src/assets/icons/arrow_back_ios.svg
- src/assets/icons/arrow_forward_ios.svg
See https://github.com/owncloud/web/issues/5165
> Add sidebar toggle icons

- docs/components/status/Components.vue
I've made components in the components overview clickable.
I cannot describe how annoyed I've been over the last months to always expand the sidebar menu when clicking through several components. Now I can go back to the overview page and click the next component.
It's also just completely weird to have a documentation overview of components but not being able to click them.
I tried to figure out what exactly happens when links are clicked in the sidebar but I could not find if there is any router of some kind involved. Anyhow the sidebar menu collapses also when clicking on links there, so this is at least not worse than the menu on the side.
I can add a changelog when you approve this otherwise.
- looked at http://localhost:6060/ and http://localhost:6060/#/oC%20Components
> Link components from overview

- build/build-system.js
- package.json
- yarn.lock
Supersedes #1611 and reduces dependencies
> Remove loading spinner from build:system

- package.json
- yarn.lock
Update vue-styleguidist to 4.41.1
> Update vue-styleguidist to 4.41.1

- src/components/avatars/OcAvatarItem.vue
Moved from a fragile, absolute placement via margin to flexbox-based centering
> Fix avatar icon alignment

- changelog/unreleased/enhancement-hover-for-filestable
- src/components/table/OcTableFiles.vue
Documents behavior & adds changelog item for #1632
> Add changelog item & example for hover in OcTableFiles

- changelog/unreleased/bugfix-context-menu-scroll
- package.json
- src/components/OcDrop.vue
- src/components/table/OcTableFiles.vue
- yarn.lock
in some cases it could happen that the screen height is not
enough to display all context menu items. This is fixed by
calculating available screen estate and makes the container scrollable
fix: https://github.com/owncloud/web/issues/5845
> fix(context menu): context menu scroll bars

- changelog/unreleased/enhancement-make-datepicker-themable
- src/components/atoms/OcDatepicker/OcDatepicker.vue
See https://github.com/owncloud/owncloud-design-system/issues/1679
> Make datepicker themable

- changelog/unreleased/bugfix-limit-select-event
- src/components/molecules/OcTable/OcTable.spec.js
- src/components/templates/OcTableFiles/OcTableFiles.spec.js
- src/components/templates/OcTableFiles/OcTableFiles.vue
Needed for batch actions in contextmenu in web
> Limit emit select to single file

- changelog/unreleased/enhancement-resource-text-weight
- src/components/atoms/OcResourceName/OcResourceName.vue
- src/components/templates/OcTableFiles/OcTableFiles.vue
This PR reduces the font weight for filenames to make the files list easier for the eye.
> Regular font weight and default text color for extensions and filenames

- changelog/unreleased/enhancement-add-accentuated-property
- src/components/molecules/OcTable/OcTable.vue
- src/tokens/ods/color.yaml
See https://github.com/owncloud/web/issues/5967
> Add accentuated property for accentuating uploaded files

- .drone.star
Node v16 is now the official LTS, let's see what CI says!
> Update NodeJS in CI to v16

- changelog/unreleased/enhancement-add-accentuated-property
- src/components/molecules/OcTable/OcTable.vue
- src/components/templates/OcTableFiles/OcTableFiles.vue
The following dates are affected: modify date, share date and deleted date.
This goes together with the Web PR https://github.com/owncloud/web/pull/6037
- Related to https://github.com/owncloud/web/issues/5672
> Add tooltips to relative dates in files table

- changelog/unreleased/enhancement-space-icon
- src/assets/icons/space.svg
> Add svg icon for spaces

- changelog/unreleased/enhancement-use-roboto
- config/docs.config.js
- docs/docs.styles.scss
- docs/docs.tokens.json
- docs/docs.tokens.scss
- docs/faq.md
- src/styles/theme/oc-text.scss
- src/tokens/docs/font.yaml
- src/utils/webFontLoader.js
- Remaining task for https://github.com/owncloud/web/issues/6100
> Switch to Roboto font

- src/components/atoms/OcAvatarCount/OcAvatarCount.vue
- src/components/atoms/OcAvatarItem/OcAvatarItem.vue
- src/components/atoms/OcSearchBar/OcSearchBar.vue
- src/components/atoms/OcSelect/OcSelect.vue
- src/components/atoms/OcSwitch/OcSwitch.vue
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcPagination/OcPagination.vue
- src/components/organisms/OcModal/OcModal.vue
- src/components/organisms/OcRecipient/OcRecipient.vue
- src/mixins/sort.scss
- src/styles/theme/background.scss
- src/tokens/ods/color.yaml
Introducing the themeSwitcher in https://github.com/owncloud/web/pull/6240 (dark/light) revealed few weak points in the ODS. This PR collects quick fixes
- Fixes #1870
- Fixes #1885
- Fixes #1887
> Fix coloring issues & add branded gradient

- package.json
- src/components/atoms/OcAvatarItem/OcAvatarItem.vue
- src/components/molecules/OcAvatarFederated/OcAvatarFederated.vue
- src/components/molecules/OcAvatarGroup/OcAvatarGroup.vue
- src/components/molecules/OcAvatarGuest/OcAvatarGuest.vue
- yarn.lock
> Fix release version in Avatar components, add missing icon import in OcAvatarItem

- changelog/unreleased/enhancement-add-drop-rounded-prop
- changelog/unreleased/enhancement-make-drops-rounded
- changelog/unreleased/enhancement-oclist-improve
- src/components/atoms/OcDrop/OcDrop.vue
- src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
- src/components/atoms/OcList/OcList.vue
- src/styles/theme/helper.scss
- src/styles/theme/oc-text.scss
We've added a border-radius for the OcDrop 
to make it rounded.
> Make OcDrop rounded / Improve OcList

- .depcheckrc
- .drone.star
- changelog/unreleased/change-drop-ie-support
- package.json
- yarn.lock
See commit messages & changelog item
> Change: Drop IE support

- build/webpack.system.conf.js
- changelog/unreleased/enhancement-export-resource-type-icon-colors
Make them available to extension developers/other (potential) users of the ODS
> Add resource icon/type/color mapping to bundle

- changelog/unreleased/enhancement-oc-drop-background
- src/components/atoms/OcDrop/OcDrop.vue
- src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
- src/styles/theme/helper.scss
> Switch OcDrop background to muted, add rounded corners helper class

- changelog/unreleased/enhancement-table-header-alignment
- src/components/atoms/_OcTableCellHead/_OcTableCellHead.vue
- src/components/molecules/OcTable/OcTable.vue
We've applied the full row height to the table header and made it vertically centered to give a more fluffy experience for the eye.
Implementation of the redesign
> Set table header to full row height and align vertically centered

- changelog/unreleased/enhancement-oc-drop-background
- src/components/atoms/OcDrop/OcDrop.vue
- src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
- src/components/molecules/OcTable/OcTable.vue
- src/styles/theme/background.scss
> Switch to 'highlight' color for OcDrop bg, use accentuate theme color for table hover

- changelog/unreleased/bugfix-oc-drop-shadow
- src/components/atoms/OcDrop/OcDrop.vue
Thanks @lookacat for the hint!
> Fix missing OcDrop shadow

- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- test case 1:
- test case 2:
- ...
> Redesign: add hover subline to breadcrumbs

- changelog/unreleased/enhancement-redesign-modal
- src/components/organisms/OcModal/OcModal.vue
- src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap
> Redesign OcModal, fix missing icons in OcModal docs

- changelog/unreleased/enhancement-modal-focus-trap
- src/components/organisms/OcModal/OcModal.vue
- src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap
Reverts owncloud/owncloud-design-system#1969
> Revert "extend modal focus-trap"

- changelog/unreleased/enhancement-redesign-breadcrumb
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
See https://github.com/owncloud/web/issues/6218
> Redesign OcBreadcrumb

- changelog/unreleased/enhancement-redesign-breadcrumb
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
Necessary to avoid unnecessary acceptance test selector butchering in https://github.com/owncloud/web/pull/6472
> Add span wrapper to content of currentPage breadcrumb btn

- README.md
- changelog/unreleased/enhancement-redesign-filestable-related-components
- src/components/molecules/OcTable/OcTable.vue
> Sort btn hover & peerDependency note

- changelog/unreleased/bugfix-mobile-breadcrumb
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
- Works towards https://github.com/owncloud/owncloud-design-system/issues/1980
> Fix icon&background color for mobile OcBreadcrumb

- changelog/unreleased/bugfix-fix-octable-sort
- src/components/molecules/OcTable/OcTable.vue
We've fixed a visual bug that caused the field sort
arrow to be always visible.
> Fix OcTable sort arrows

- changelog/unreleased/bugfix-modal-initial-focus
- src/components/organisms/OcModal/OcModal.vue
- src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap
Initial focus of OcModal with text field was broken.
> Fix initial focus in OcModal

- changelog/unreleased/bugfix-oc-modal-overflow
- src/components/organisms/OcModal/OcModal.vue
> Remove overflow:hidden from OcModal

- changelog/unreleased/bugfix-disabled-ocselect-background
- src/components/atoms/OcSelect/OcSelect.vue
Came up while working on https://github.com/owncloud/web/issues/6495
> Respect theming for disabled OcSelect background

- changelog/unreleased/enhanchement-oc-tag-size
- test case 1:
- test case 2:
- ...
> Replace oc-card with oc-tag as it was faulty

- changelog/unreleased/enhancement-redesign-ghost-element
- src/components/atoms/_OcGhostElement/_OcGhostElement.vue
We've redesigned OcGhostElement to use OcResourceIcon and
to display better preview of the items that have been dragged
- Now:
Darkmode: 3 items selected (folder):
Darkmode: 3 items selected (file):
Lightmode 2 items selected:
- Before
> Redesign _OcGhostElement

- changelog/unreleased/enhancement-add-selection-range-for-modal-and-textinput
- src/components/molecules/OcTextInput/OcTextInput.vue
- src/components/organisms/OcModal/OcModal.vue
See https://github.com/owncloud/web/issues/6729
- Works towards https://github.com/owncloud/web/issues/6729
> Add selection range for OcModal and OcTextInput

- yarn.lock
supersede https://github.com/owncloud/owncloud-design-system/pull/2097 and https://github.com/owncloud/owncloud-design-system/pull/2074 which didn't manage to get any CI run...
> Supersede dependabot branches

- yarn.lock
> Supersede #2132

- changelog/unreleased/change-redesign-contextual-helper
- src/components/atoms/OcContextualHelper/OcContextualHelper.vue
- test case 1:
- test case 2:
- ...
> Set font-weight explicit

- changelog/unreleased/enhancement-avatar-font-weight-normal
- src/components/molecules/OcAvatar/OcAvatar.vue
Enhancement: Adjust avatar font weight from bold to normal
- Part of: https://github.com/owncloud/web/issues/7340
- test case 1:
- test case 2:
- ...
> OcAvatar set font-weight to normal

- changelog/unreleased/enhancement-add-rounded-oc-tag
- src/components/atoms/OcTag/OcTag.vue
- Works towards https://github.com/owncloud/web/issues/7169
> Add rounded property for tags

- changelog/unreleased/enhancement-use-inter
Use single-storey-letter "a" so that the letter "a" is aligned with the "rounded" letters and figures
> added Use single-storey-letter "a"

- changelog/unreleased/bugfix-firefox-drag-drop
- src/components/atoms/OcResourceLink/OcResourceLink.vue
- src/components/organisms/OcResource/__snapshots__/OcResource.spec.js.snap
See https://github.com/owncloud/web/issues/7495
- Fixes https://github.com/owncloud/web/issues/7495
> Firefox drag & drop move of folders not possible

- changelog/unreleased/enhancement-breadcrumb-spacing
- src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
- src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
Part of https://github.com/owncloud/web/pull/7684.
https://github.com/owncloud/web/issues/7676
https://github.com/owncloud/web/issues/7525
> Adjust breadcrumbs spacing

- src/components/organisms/OcResource/OcResource.vue
- test case 1:
- test case 2:
- ...
> Emit event on folder link clicked

- changelog/unreleased/enhancement-remove-button-border
- changelog/unreleased/enhancement-select-hover-state
- src/components/atoms/OcButton/OcButton.vue
- src/components/atoms/OcSelect/OcSelect.vue
* [Redesign hover-state for OcSelect component](https://github.com/owncloud/owncloud-design-system/pull/2345/commits/d68be867e2097b1be6c5f68c6140118993eef33e)
* [Remove outer border for buttons](https://github.com/owncloud/owncloud-design-system/commit/e46218bd7522588f09df4eef754986fbb83500de)
- https://github.com/owncloud/web/issues/7353
- https://github.com/owncloud/web/issues/7373
> Align components with design in Figma

- README.md
Updating the README to announce that the code moved to the web repo.
Fixes https://github.com/owncloud/owncloud-design-system/issues/2369
> docs: update README to announce new repo
