owncloud/owncloud-design-system

docs/docs.styles.scss

As ownClouds colors contain light gray in its color pallet, I recommend a white background to better distinguish colors.

Improve contrast in demo content

---

package.json

Fix these warning in yarn install:
```
[4/5] Linking dependencies...
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
[5/5] Building fresh packages...

yarn add jest-resolve jest-haste-map

---

src/elements/OcMenuItem.vue
src/patterns/OcMenu.vue
src/templates/Files.vue

close #101 
- introduce `oc-menu-item` element for usage inside `oc-menu`
- introduce subnav slot in  `oc-menu-item` including `ul`

oc-menu-item for usage in subnav slot inside oc-menu

---

src/elements/OcFile.vue
src/patterns/OcFileActions.vue
src/patterns/OcFileList.vue
src/templates/Files.vue

This is a first approach:
Several questions:
1. I combined an `offcanvas`, `nav` and a `span` for this. It does slide in from the left, but we could use `mode: none` to make it just appear. The css for sliding the div in from the bottom eludes me. I already added css to make the canvas appear at the bottom, see [the upstream issue comment](https://github.com/uikit/uikit/issues/3445#issuecomment-437058627). Not the cleanest approach. And it is not modal ... if we even want that.
2. Does using an offcanvas make it easier for mobile navigation?
3. What about the label?
a. How do we combine the text with the filename? I currently use a simple string replace.
b. How do wo translate the "Open %s in" string?
4. How do we always close the action items offcanvas when an action item is clicked. …

add file actions and items

---

package.json
yarn.lock

Reverts owncloud/owncloud-design-system#152
some upstream change is breaking the generated docs
Reverting this to get it working again and we can take care about the upgrade later

Revert "Bump vue-styleguidist from 3.11.2 to 3.11.3"

---

.drone.yml

This will publish ods to npmjs repo. Currently each master branch push will be built and pushed there ....
Support for tags will follow ....

Add npm publish steps

---

src/elements/OcButton.vue
src/styles/theme/_variables.scss
src/styles/theme/oc-button.scss

Propagate token color to theme
Fixes: https://github.com/owncloud/owncloud-design-system/issues/193

Ligher icon in disabled buttons

---

docs/components/Preview.js

I made a mistake while rebasing my changes onto yours in the feature/open-in-new-browser and removed the fix for disappearing button. Sorry. Here is it back.

Fixed disappearing button

---

src/elements/OcNavItem.vue

Added slot in oc-nav-item to enable putting content outside of `<a>` tag

Added slot for extra content

---

src/styles/theme/oc-topbar.scss

Add a min-height to the top-bar so that it doesn't collapse in IE11

[IE11] Give topbar a min height

---

src/styles/theme/oc-topbar.scss

Having pointer cursor at user is confusing when there is no action triggered by clicking on it.

Removed pointer from user

---

src/patterns/OcAutocomplete.vue

Show exact matches in the dropdown as well:
Fixes: https://github.com/owncloud/smb_acl_frontend/issues/76

Show exact matches in ocAutocomplete

---

src/elements/OCDrop.vue

Fixes element not properly aligning with the boundary.
* Allow propper boundary-allignment
---
_Alignment example with search dropdown in small viewports_

Align ocDrop Element to its boundary

---

src/elements/OcButton.vue
src/elements/OcTextInput.vue

The `stopClassPropagation` removes all styles from the component in order to maintain functionality and apply styles from the pattern without tedious overrides.
Upstream Changes from Customer theme

[Upstream] Add stopClassPropagation to help pattern styling

---

docs/docs.styles.scss

Fixes the issue, where Phoenix body layout values negatively affect the documentation.
Namely not being able to scroll ODS Docs anymore.

force body inherit overflow and height values in docs.styles

---

src/patterns/OcAppSideBar.vue

If the button would need the margin/padding it can be added either in theme or if user adds custom close element with it. This way we don't need to remove it in case we are using padding for the whole sidebar.

Removed right margin from sidebar close button

---

src/patterns/OcAutocomplete.vue

Added optional prop to assign class to dropdown in autocomplete.
In some cases we need to style the dropdown differently and this way we can simply do it by assigning new class to it and don't need to fallback to theming which could be bad practice in some cases. (e. g. assigning class "uk-width-1-1" to have the same width as input)

Autocomplete dropdown class

---

src/patterns/OcAutocomplete.vue

Removed "1 more result" key from autocomplete and added overflowingMatches key to data of component.
With the power of gettext in Phoenix we don't need two different keys for the text "more results" since it can handle plural cases. For this we need to get number of overflowing matches. To access it better in Phoenix, I think it makes sense to make it as a key in data of the component - developers then don't need to access this value with `$_ocAutocomplete_matchesOverflowing` but simply with `data.overflowingMatches` => seems nicer to me.
- Fixes https://github.com/owncloud/phoenix/issues/1511

Fix two 1s in more result text in autocomplete

---

src/elements/OCAvatar.vue

Since oc-img component requires src as a prop it needs to be in avatar as well.

Added src prop to avatar

---

src/elements/OcSpinner.vue

This PR/commit adds:
* role and tabindex attributes to the spinner component
* makes the ariaLabel prop required
* The reasoning behind it, in form of documentation as an example of the accessible use of this component

Add accessibility documentation and attributes for OcSpinner

---

src/styles/theme/oc-app-bar.scss

Adjust a min-height instead of a fixed height to all app bars. This is needed on narrow screens

Adjust appbar to a variable height

---

config/docs.config.js
docs/i18n.md

Adding general rtl documentation, regarding CSS, for https://github.com/owncloud/phoenix/issues/279

Add general rtl docs

---

src/elements/OCStar.vue
src/elements/OcButton.vue
src/elements/OcStarToggle.vue
src/styles/theme/helper.scss
src/styles/theme/oc-button.scss

* Simplification of OcStar
* New scss helper function for "raw" buttons
* New: OcStarToggle component as a button `role="switch"` conveying its state with `aria-checked="true|false"
In ODS OcSwitch is an image that reacts to a toggle button, but is not the toggle button itself. OcStarToggle matches Phoenix's current implementation of the star being the interactive control (alas, not a button. But this is what this OR is for).
Discussion started in this PR: https://github.com/owncloud/owncloud-design-system/pull/481#issuecomment-544442414
[Article by Heydon Pickering, longread](https://inclusive-components.design/toggle-button/#thisdoesntquitefeelright)

Refactor and document OcStar(Toggle)

---

src/patterns/OcAutocomplete.vue

Will be needed for usability, saving clicks by automatically setting the focus there.

Focus method for oc-autocomplete

---

src/elements/OcTabbed.vue
src/elements/OcTabbedPanel.vue
src/elements/OcTabbedTab.vue
src/styles/_owncloud.scss
src/styles/theme/_oc-tabbed.scss
src/styles/theme/helper.scss

Establishes:
* New tab component `oc-tabbed`
* New tab-item component `oc-tabbed-tab`
* New panel-item component `oc-tabbed-panel`
Structure according to the briefing by @PVince81 
Keyboard behaviour, ARIA roles, properties and states according to the [Authoring Practice](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.htmll) 
Intention for establishing new components: Trying to avoid to break phoenix by using the `oc-tab-item` namespace since the new component is much more complex than the existing one.

Adds new tab component tabbed including child components, for #535

---

src/elements/OcHiddenAnnouncer.vue
src/elements/OcProgress.vue
src/styles/_owncloud.scss
src/styles/theme/_oc-progress.scss

Improves screen reader communication of `OcProgress` and adds a generic live region component (boths first use will be https://github.com/owncloud/phoenix/pull/2542).
Double semantics in OcProgress.vue  (`<progress role="progressbar" ... />`) is to remedy a shortcoming in JAWS screenreader.

Improve accessibility of OgProgress and add live region component, for #536

---

src/elements/OcCheckbox.vue
src/elements/OcRadio.vue
src/elements/OcSwitch.vue
src/elements/OcTextInput.vue
src/elements/OcTextarea.vue

* Make labels required. Unfortunately there is no way to check for the slot's content in prop validation. Vue Docs: "Note that props are validated before a component instance is created, so instance properties (e.g. data, computed, etc) will not be available inside default or validator functions."
* Distinguish between placeholder and label
* Improve example code with labels
* Prevent explicit and aria-label at the same time

Various accessibility improvements regarding labels

---

src/assets/icons/apps.svg
src/elements/OCAvatar.vue
src/pages/Files.vue
src/styles/theme/oc-app-menu.scss

- App switcher goes to the top right.
- User menu on top right.
- App specific navigation stays in the left sidebar.
- Supersedes https://github.com/owncloud/owncloud-design-system/pull/532

Separate the menus

---

src/elements/OCNotificationMessage.vue
src/elements/OCNotifications.vue
src/elements/OcIcon.vue
src/styles/theme/helper.scss

* New: added `aria-live` and `role` attributes to the part of the notification container that has text inside it
* New: The amount of interrupting the screen reader (assertive, polite) is indirectly controllable with `<oc-notification-message>`'s `status`: Only "danger" creates an assertive screen reader notification that interrupts the screen reader output
* Changed: The close button is now an actual button (instead of link)
* Changed: The close button has an accessible name of "Close" 
* Added: Documentation

Scaffold accessibility documentation for OcNotification/Message components

---

src/patterns/OcSearchBar.vue

* New: A (conditional) landmark role of search, including a prop to disable it
* Changed: The existence of the button is not optional anymore, only whether it is visually perceivable is. Therefore I split the existing `button` prop into `buttonHidden` and `buttonLabel` (Hopefully this will not cause a chain reaction in phoenix)
* Documentation/reasoning of both
Please ping me if this change was too radical since it changes existing ways of using components/APIs

Scaffold accessibility documentation for OcSearchBar pattern

---

src/patterns/OcAutocomplete.vue

When clicking on the "more results" button, prevent the click event to
propagate and so prevent the dropdown to close.
Added example block to bring into attention the existence of the
overflow.

Fix autocomplete more results button

---

src/patterns/OcAutocomplete.vue

Context: https://github.com/owncloud/phoenix/issues/2593
Autocomplete pattern based on [WAI-ARIA authoring practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html)
Please note: after selection of a suggestion, the selected value will now be filled into the `input` part of the autocomplete. This behaviour can bis disabled by setting `fillOnSelection="false"`. Be aware that when doing so the component will be much less accessible, and the information about a successful selection must be communicated to screen readers, for example with help of a live region (`<oc-hidden-announcer>`)

Improve accessibility of ocAutocomplete

---

src/elements/OCAvatar.vue

When [switching to vue-avatar](#592) the attribute name is now a different one.

Use the correct attribute for size

---

src/elements/OcSpinner.vue
src/styles/_owncloud.scss
src/styles/theme/oc-spinner.scss

Dropped spinner from UIkit and implemented custom solution.
UIkit spinner wasn't animated in IE 11 since it was done via SVG animations. This custom solution is compatible with IE 11. Also, UIkit is supposed to be replaced anyway so this can be a start 🙂 
- Fixes: #423
- Refs: #538

Implemented custom spinner

---

src/elements/OcDatepicker.vue

Implementation for https://github.com/owncloud/owncloud-design-system/issues/617
As the used datepicker component already binds `$attrs` to the input field, it is sufficient to just add a `placeholder` property and bind it to the `datetime` tag. Copied the placeholder property from `OcTextInput` in order to have identical documentation.
Can be tested by running ods and inspecting the input field of a datepicker with placeholder variable.

Provide placeholder property and bind it into the datepicker

---

src/elements/OcIcon.vue
src/pages/Files.vue
src/styles/theme/oc-icon.scss
src/tokens/color.yml

This idea brings all share indicators into a separate column.
- which resource is shared: see whether column icons are present
- what kind of share ? (user/link): see icon types in column
- is the share applied from a parent instead of directly ? => see reduced opacity
- optional: incoming/outgoing ? icon color
- who has access ?
- open right sidebar for resource
- list of collaborators sums up collaborators of parents (+ via jump)
- list of links sums up links of parents

Share indicators + new icon colors "active" and "passive"

---

src/elements/OcBreadcrumb.vue
src/styles/theme/oc-breadcrumb.scss

Added overflow: hidden on the main element of the oc-breadcrumb to make
sure that it can ellipsize its content in responsive mode.
Before this fix it would just overflow.
You can also try this in Phoenix by having long folder names and adding "overflow:hidden" on that element and see the difference.

Fix breadcrumb component ellipsis

---

src/elements/OcIcon.vue
src/styles/theme/oc-icon.scss

Added "xlarge" with 96px.
Added "xxlarge" with 192px.
Adjusted indent in OcIcon.
Changed icon size presentation to use a tabular layout.

Add bigger icon sizes

---

src/elements/OcIcon.vue
src/elements/OcSpinner.vue
src/styles/theme/oc-icon.scss
src/styles/theme/oc-spinner.scss

Fix sizes of `oc-spinner`, see https://github.com/owncloud/owncloud-design-system/issues/631
Also introduced more sizes. `xsmall` for oc-icon and `xsmall` and `xxlarge` for oc-spinner, so that both components have the same size options, as well as producing same size html.

Align sizes of oc-spinner with those of oc-icon

---

src/patterns/OcAutocomplete.vue

Set missing `aria-label` on oc-spinner in oc-autocomplete. span got an `aria-hidden` because for a screenreader it's sufficient to have the label from the spinner, don't need the same text again in the span.

Set aria-label on oc-spinner in oc-autocomplete

---

src/patterns/OcAutocomplete.vue

On item selection from the autocomplete dropdown, the input field needs to be either reset or filled with the selected value. Keeping the given input after selection looks like an error state.
We already have the case that the selection gets applied to the input field, when `fillOnSelection` is `true` (default). This PR fixes the other case, i.e. clearing the input field on selection when `fillOnSelection` is `false`.

Reset input on selection if fillOnSelection=false

---

docs/i18n.md

Added docs about escaping translations

---

changelog/unreleased/652
src/elements/OcButton.vue
src/styles/theme/oc-button.scss

UIKit is adding text-transform: uppercase on all buttons.
This commit removes it in the standard theme.
Not sure if the theme is the right place though...

Remove uppercase on buttons

---

changelog/unreleased/654
src/elements/OcButton.vue
src/styles/theme/oc-button.scss

Raw variation of buttons have no border, so they now also don't have a size enforced to avoid needless white space.

Removed size for oc-button with raw variation

---

changelog/unreleased/660
src/pages/Files.vue
src/styles/theme/main.scss

The Chrome scrollbar is now thinner to look like the Firefox one.
Adjusted Files page to be able to demonstrate the scrollbar styles.
Note: I heard that this would only affect Windows and Linux as Macs already have the proper style.
On my Linux box now the scrollbars look like this:
Fixes https://github.com/owncloud/phoenix/issues/3045

Make scrollbar styles more consistent

---

changelog/unreleased/681
src/elements/OcIcon.vue

Instead of loading the icon image from the URL only when mounted, the
component now also supports changing the URL after mounting. The watcher
will trigger a reload of the image whenever the URL property changed.

Reload icon image when its url prop changed

---

changelog/unreleased/688
changelog/unreleased/689
src/elements/OcTextInput.vue
src/styles/theme/oc-text-input.scss

This PR introduces properties for the `oc-text-input` component, allowing to provide an error message or warning message, that will then be shown below the input field. In addition to that, the space below the input field can be set to a min height, so that the space is always reserved (at least for one line) no matter if an error or warning message is currently visible or not. Property is off by default, so that the input doesn't take up more space than it would have needed in the first place.
Issue is: https://github.com/owncloud/owncloud-design-system/issues/689
Also I noticed that the component was not present in the generated docs. This was due to a compilation warning in `@focus` of the input. Fixed it by moving the two commands into the method instead of having two commands inline …

Introduce error and warning message below input

---

changelog/unreleased/710
src/patterns/OcAutocomplete.vue

OcAutocomplete was broken because an aliased import was not working properly.

Fix OcAutocomplete

---

changelog/unreleased/modal-confirm-without-input-ref
src/elements/OcModal.vue

Otherwise, the confirm would throw an error because of trying to reach non-existing ref.

Do not emit value if input is disabled in modal

---

docs/utils/activeNav.spec.js
docs/utils/filterSearch.spec.js
docs/utils/statusLabels.spec.js
package.json
yarn.lock

With the new release of `vue-test-utils` there were some deprecated parts which needed to be adjusted and also `optimist` has become a required dependency of one of the already included packages.

Updated all deps

---

changelog/unreleased/modal-disable-input-when-error
changelog/unreleased/modal-input-event
changelog/unreleased/modal-input-model
src/elements/OcModal.vue

Properly handle input value via v-model, use `input` event and disable confirm button in case of an error.

Fixed prop mutation, wrong event and confirm button protection in the modal

---

changelog/unreleased/remove-input-custom-events
src/elements/OcModal.vue
src/elements/OcTextInput.vue

Since they are passed via listeners there is no need for them.

Removed change and keydown events from input listeners

---

docs/docs.styles.scss

There were a couple of selectors using href in the docs styles. They weren't escaping spaces though. This fixes it. Later I'd like to dig deeper to not include those sections in the sidebar but still include them in the final bundle but for now, I'd see this as sufficient solution.

Fixed href selectors in styles

---

changelog/unreleased/modal-focus
src/elements/OcModal.vue
src/elements/__snapshots__/OcModal.spec.js.snap
src/styles/theme/oc-modal.scss

When the modal is mounted, it receives automatically a focus. The focus is sent directly to the modal itself so skipping the wrapping div which works only as a background.
Refs https://github.com/owncloud/phoenix/issues/2263

Automatically focus modal when mounted

---

src/styles/theme/oc-modal.scss
src/tokens/color.yml

just a typo fix in a variable name. double checked in phoenix, that it's not directly used.

Fix typo in color name

---

changelog/unreleased/brand-and-interaction-colors
changelog/unreleased/improved-buttons
changelog/unreleased/logo-clearspace
changelog/unreleased/oc-ci-font
src/elements/OcButton.vue
src/styles/theme/_variables.scss
src/styles/theme/oc-button.scss
src/styles/theme/oc-sidebar.scss
src/tokens/color.yml
src/tokens/paddings.yml
src/tokens/size.yml

Bring oC CI into the default theme, improve buttons design and improve the size of the logo in the sidebar. This PR contains quite a few changes but they're quite small in size so I merged them into one PR.
- refs #786
- refs #546
- closes #785
- closes #784 
- closes #777
- Closes #796

Add brand colors and xlarge padding token and increase logo clearspace

---

changelog/unreleased/sidebar-main-content
src/elements/OcSidebar.spec.js
src/elements/OcSidebar.vue
src/elements/__snapshots__/OcSidebar.spec.js.snap
src/styles/theme/oc-sidebar.scss

The navigation inside of the sidebar can be replaced with a custom content via the slot called `mainContent`. In this slot can be included e.g. a short description of the product, guide the user through the current action, etc.

Add mainContent slot into sidebar

---

changelog/unreleased/lead-variation-breadcrumbs
src/elements/OcBreadcrumb.spec.js
src/elements/OcBreadcrumb.vue
src/elements/__snapshots__/OcBreadcrumb.spec.js.snap
src/styles/theme/oc-breadcrumb.scss

Enable usage of breadcrumbs as a title of page.

Add lead breadcrumb variation

---

changelog/unreleased/new-progress-bar
src/elements/OcProgress.spec.js
src/elements/OcProgress.vue
src/elements/__snapshots__/OcProgress.spec.js.snap
src/styles/_owncloud.scss
src/styles/theme/_oc-progress.scss
src/styles/theme/oc-progress.scss

We've added new variations and sizes of the progress bar component. Variations change the color of the progress bar and can be either `primary` or `warning`. Sizes affect the height of the progress bar where it can be either `default` or `small`.

Add new variations and sizes of progress bar

---

changelog/unreleased/reworked-button
src/elements/OcButton.vue
src/styles/theme/helper.scss
src/styles/theme/oc-button.scss
src/tokens/color.yml

Having complete freedom when adding icons and using the css grid to preserve our defined gutters.
- Refs #538

Remove icon prop, UIKit styles and add css grid into buttons

---

src/elements/OcSidebar.spec.js
src/elements/OcSidebar.vue
src/elements/__snapshots__/OcSidebar.spec.js.snap

We introduced a new property for the sidebar for hiding the navigation
entirely. The internal logic of not showing the navigation under certain
circumstances has been removed.
Please note that this is a breaking change. The navigation inside the sidebar might become visible in situations where it was not visible before.

Introduce property for hiding the navigation in the sidebar

---

changelog/1.10.0_2020-09-16/reworked-button
jest.conf.js
package.json
src/elements/OcButton.vue
src/elements/OcGrid.vue
src/elements/OcSidebar.spec.js
src/elements/OcSidebar.vue
src/elements/OcSidebarNavItem.vue
src/pages/Files.vue
src/patterns/OcAppBar.vue
src/patterns/OcAppSideBar.vue
src/patterns/OcFileList.vue
src/patterns/_OcTopBarLogo.vue
yarn.lock

So that it doesn't need to be used with @click.native

Fix click event in oc-button

---

changelog/unreleased/wrong-extend
src/styles/theme/oc-user-menu.scss

We've fixed the wrong extend syntax in oc-user-menu which was written in LESS.
This syntax caused an issue with loading all styles and e.g. margin utility classes were not working.

Fix wrong extend syntax

---

changelog/unreleased/button-flex
src/styles/theme/oc-button.scss

We've started using flexbox in the button component instead of css grid to position children correctly.
This gives us more flexibility for the alignment of children.

Use flexbox in buttons

---

src/styles/theme/oc-datepicker.scss

This changes the squared off border of the date input field (which opens a calendar picker) to be rounded the same as text inputs.  This makes them look better and more consistent when used in a form with other inputs (that have the same border radius).
**Before** (200% zoom)
**After** (200% zoom)

Add rounded border to date input field

---

docs/components/Preview.js

The "toggle fullscreen button" in docs was useful when we were still having "pages" section where was a content spanning the whole pages. Since they are removed I do not see a point in having this feature anymore. This cleans a bit the examples view.

Remove toggle fullscreen button

---

changelog/2.0.1_2020-12-02/fix-docs
package.json

Version bump for release 2.0.1 which fixes broken `component` docs.

Version bump for release 2.0.1

---

package.json
yarn.lock

As it's pretty standard that linting is happening in our IDEs and it's a first step we run in tests which on failure fails the whole test, we want to drop this in order to not run some hooks which don't bring much benefits.

Remove lint pre-commit hook

---

changelog/2.1.2_2020-01-21/pin-uikit
package.json
yarn.lock

We've pinned the version of UIkit to 3.5.16.
The reason for this is that the version 3.5.17 caused a regression to our autocomplete component.
Since we want to remove UIkit from the ODS in the near future, we are not taking the time to come up with a fix.
We do not plan to upgrade UIkit anymore.

Pin UIkit to v3.5.16

---

changelog/unreleased/remove-basic-styles
src/styles/_owncloud.scss
src/styles/theme/main.scss
src/styles/theme/oc-app-container.scss

We've removed styles from the body element and from the #oc-content element. We were forcing styles on a global level which were too specific and because of that limited the usage of the design system. Any specific styling like that should be done in the consuming app.

Remove basic styles

---

changelog/unreleased/remove-basic-styles copy
src/components/resource/OcResource.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

We've merged the resource target route path with the folder path in the `router-link`. When passing the path as a parameter, it wasn't being recognised and the navigation just pointed to the target route path. By explicitly merging them, we make sure that the navigation behaves as expected.
Additional changes in this PR:
- Encode the path
- Stop propagation for the links to prevent opening sidebar in oC Web

Merge resource target path with folder path

---

changelog/unreleased/dynamic-header-position
src/components/table/OcTable.vue
src/components/table/OcTableFiles.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

We've added a prop which is defining the top position of the table header if the `sticky` prop is set to `true`.

Add dynamic top position to table header

---

changelog/unreleased/table-cells-keys
src/components/resource/OcResource.vue
src/components/table/OcTable.vue

We've started using values as keys for the table celss so that they are reactive to the changes in values.

Use values as keys

---

changelog/unreleased/table-files-selection-model
src/components/table/OcTableFiles.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

We changed the selection model of the `oc-table-files` component to use resources instead of their ids.

Use resources instead of ids as selection model

---

CHANGELOG.md
changelog/unreleased/fix-button-hover
src/styles/theme/oc-button.scss

Fixes #899 (but there's more to it, see details below)
I tested the changes locally editing the code preview on the [OcButton](http://localhost:6060/#/oC%20Components/OcButton), as
```html
<oc-button variation="primary" class="oc-mr-s" type="a">Primary button (a)</oc-button>
<oc-button variation="primary" class="oc-mr-s" type="button">Primary button (button)</oc-button>
```
Having resolved the `color` problem I realized that `text-decoration` differs between `type="a"` and `type="button"`, so I decided to explicitly set it to `none` (as this is the case with other button types in use).
Just now I made the mistake and did some further investigation since oc-buttons can also be `"danger"` or `"inverse"` (default), and there's more odd behaviour with `color`, `text-decoration` but also …

Explicitly set oc-button:hover color & text-decoration

---

changelog/unreleased/router-link-object
src/components/resource/OcResource.spec.js
src/components/resource/OcResource.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

We've changed the `targetRoute` prop in the `oc-resource` component to accept object instead of a string. This object is now accepting keys `name`, `params` and `query`. Only `name` is required. All keys are then passed to the router link which enables using more complex routes.

Pass route object instead of string in targetRoute

---

src/components/resource/OcResource.vue
src/components/table/OcTableFiles.vue

To enforce re-render in case the resource has received a preview.

Add key to resource slot

---

changelog/unreleased/fix-table-in-icons-docs
src/components/OcIcon.vue

Discovered that the (now outdated) `<oc-table>` component on the [OcIcon Documentation page](https://owncloud.design/#/oC%20Components/OcIcon) was broken.
Discussed it with @kulmann today and he suggested we'd use the new `<oc-table-simple>` there.

Introduce <oc-table-simple> to fix OcIcon showcases

---

src/components/OcSidebar.vue

The *class="uk-height-1-1"* in OcSidebar.vue translates to `height: 100;` and is outruled by `.oc-sidebar`'s `height: 100vh;`. It is also only used in the design system repo, not in web.
@LukasHirt do we need a CHANGELOG item for such minor fixes/documentation corrections, too?

Remove overwritten ui-kit class from OcSidebar.vue

---

docs/docs.styles.scss

Ugly stuff happening here, the `vueds-active` class is attached and instantly replaced on the first visit of toplevel nav items...
This partly fixes #812 (doesn't feel like it deserves a changelog item, though).

Prevent having to double-click on toplevel nav items

---

changelog/unreleased/enhancement-radio-accessibility
src/components/OcRadio.vue

Add **id** and **for** properties to label
Add **aria-checked**, **aria-labelledby,**  **aria-disabled** property to input

Add aria properties to radio input

---

changelog/unreleased/enhancement-textinput-labels-and-description
src/components/OcAccordion.vue
src/components/OcTextInput.vue
src/components/__snapshots__/OcModal.spec.js.snap
src/styles/theme/oc-text-input.scss

* Remove placeholders
* Add required label to text inputs
* Add optional description message to text inputs
* Add `aria-describedby` which either references the description (if given), or an error/warning (if given)
* Add `aria-invalid` property

Implement labels and descriptions for text input fields

---

changelog/3.2.1_2021-03-17/bugfix-folder-names
package.json
src/components/resource/OcResource.vue
src/components/resource/OcResourceName.spec.js
src/components/resource/OcResourceName.vue
src/components/resource/__snapshots__/OcResourceName.spec.js.snap
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

This PR fixes a visual bug with displaying folder names that contain a dot (`.`). Most importantly it also adds a `resource-type` attribute to the oc-resource-name component which is required for testing. Otherwise we don't have a way to detect if a resource is a file or folder.
We need to create a release v3.2.1 from this PR and merge it back to master after the release. Do not merge until the release is done. Current master contains changes that we can't release, yet.

Release 3.2.1

---

changelog/unreleased/change-autocomplete-label
src/components/OcAutocomplete.vue
src/styles/theme/oc-autocomplete.scss

Adding the label "from the outside" is not a11y compliant as you cannot get the id of the actual input element which therefore cannot be referenced via `for`. This is a breaking change though as I renamed `aria-label` to `label`. We could leave it, but technically it's not aria anymore now.
This change also removes all the unnecessary prefixes which were used in the component.
Needed for https://github.com/owncloud/web/issues/4329:
> "Personen hinzufügen" is a `<label>`, but points (via for) to a `<div>` instead of an input.

Add label to the autocomplete component

---

changelog/unreleased/enhancement-aria-label-for-breadcrumb
src/components/OcBreadcrumb.vue

Fixes one part of https://github.com/owncloud/web/issues/4329
> Starting point (home link) of bread crumb has no link text, neither visually nor programmatically.

Add aria label to the home icon within the breadcrumb

---

changelog/3.2.2_2021-03-22/bugfix-links-in-avatar-group
package.json
src/components/avatars/OcAvatarGroup.vue

This PR fixes the tooltip of the oc-avatar-group in case it was only displaying links.
We'll need to create a release from this branch and merge it back to master after the release. Do not merge until then.

Fix avatar group tooltip which only has links

---

changelog/unreleased/enhancement-alert-accessibility
src/components/OCAlert.vue
src/components/__snapshots__/OCAlert.spec.js.snap

Similar to the changes in https://github.com/owncloud/owncloud-design-system/pull/1164
* Make "close"-button of an alert accessible via keyboard
* Remove the "uk-close" icon as it is not a11y-compliant

Make alert component a11y-compliant

---

changelog/unreleased/enhancement-element-nesting
src/components/OCDrop.vue
src/components/OcAccordionItem.vue
src/components/resource/OcResourceName.vue
src/components/resource/__snapshots__/OcResourceName.spec.js.snap
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

Fixes the nesting issues coming from the ODS mentioned in https://github.com/owncloud/web/issues/4345
For now this should be all in the ODS. However, it is possible some more adjustments are needed. Need to dig into Oc Web first 👀 
On a side note: Feels a bit weird to use flexbox on a `<span>` element in `OcAccordion`. But it seems to be legit. Keeping the `<div>` tags would require a change in the parent component, which currently can be any `<h1-6>` element.

Fix nesting on html elements

---

changelog/unreleased/enhancement-themable-colors
jest.conf.js
src/system.js
src/system.spec.js

Basic building block of initializing the ODS with themeOptions, by creating custom CSS props and overwriting the default color values.
Testing for the positive already works, checking for (un-over-written) default values doesn't work yet.
Depends on
- #1140 
- [#4822 in web](https://github.com/owncloud/web/pull/4822)

Create custom CSS props from themeOptions

---

changelog/unreleased/enhancement-omit-placeholders-in-modal
changelog/unreleased/enhancement-remove-placeholders-from-ocmodal
src/components/OcModal.vue

Making the behavior consistent with other usages of input-fields within the ODS

Drop placeholders in favor of descriptionMessages in OcModal

---

changelog/unreleased/bugfix-links-in-avatar-group
src/components/avatars/OcAvatarGroup.spec.js
src/components/avatars/OcAvatarGroup.vue
src/components/avatars/__snapshots__/OcAvatarGroup.spec.js.snap

The oc-avatar-group was showing all link, ignoring the `maxDisplayed` property. Fixed by properly cutting off the items used for rendering avatars. Added some tests to verify the behaviour at least on the tooltips.

Fix links count in avatar group

---

build/webpack.base.conf.js
changelog/unreleased/bugfix-oc-icon-loading
src/components/OcIcon.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

the pr changed the way how svg images get loaded in oc-icon.
Before this, svg images where transformed to data url's by webpack.
Now we use require to inline them which prevents the browser to do a XMLHttpRequest and no additional tweaking of content-security-police is required anymore.

use html-loader for svg images

---

build/webpack.system.conf.js
changelog/unreleased/enhancement-export-translations

To test this locally, run `yarn build:system` and check that `dist/system/translations.json` exists

Add translations to dist folder when building

---

.depcheckrc
changelog/unreleased/enhancement-peer-dependencies
package.json
src/components/resource/OcResourceSize.vue
yarn.lock

before this pr the package.json contained a lot of unnecessary dependencies which where hard linked.
This pr moves them to the peerDependencies and let the consuming application decide which patch or minor version to use.
We also had a lot of unused dependencies before.
Because of the way dependency management works this pr introduces breaking changes and a major release is required.

cleanup package.json and move all dependencies to peerDependencies

---

.drone.star

Publish of `v6.0.0` failed in CI with an error that I suspect to be due to an old node version in the CI pipeline
Error:
```sh
SyntaxError: Unexpected token '.'
in
color.lighten(parseInt(attributes?.transform?.lighten) || 0)
```
in https://drone.owncloud.com/owncloud/owncloud-design-system/2527/2/2
We used webhippie's latest node image which was updated 10 months ago anyways: https://hub.docker.com/r/webhippie/nodejs/tags?page=1&ordering=last_updated

Use newer nodejs images in CI

---

changelog/unreleased/enhancement-files-table-a11y
src/components/OcStatusIndicators.vue
src/components/resource/OcResource.vue
src/components/table/OcTableFiles.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

* Add accessible description in case a resource link opens in a new window
* Add accessible description for status indicators
* Adjust some of the labels to make them more descriptive
* Fix broken outline (focus) on directories
Note that the keyboard navigation for directories in ODS will most likely not work because the `router-link` component fails to transform `to=""` to `href=""`. It's working in Web though.

Enhance accessibility for the files table and its contents

---

changelog/unreleased/change-oc-breadcrumb-a11y
src/components/OcBreadcrumb.vue
src/components/__snapshots__/OcBreadcrumb.spec.js.snap

* Replace unordered list element with ordered list element
* Add nav surrounding tag
* Add aria-current='page' to the last element 
* Remove default home breadcrumb 
* Allow keyboard navigation (as well for mobile)
fixes https://github.com/owncloud/owncloud-design-system/issues/866
fixes https://github.com/owncloud/owncloud-design-system/issues/849
fixes https://github.com/owncloud/owncloud-design-system/issues/1170

Enhance oc-breadcrumb a11y 

---

changelog/unreleased/enhancement-modal-focus-trap
package.json
src/components/OcModal.vue
src/components/__snapshots__/OcModal.spec.js.snap
yarn.lock

We've added [Vue focus trap library](https://github.com/posva/focus-trap-vue) to trap the keyboard navigation inside of the modal.
To enable the focus trap, use prop `focusTrapActive`.

Add modal focus trap

---

changelog/unreleased/enhancement-breadcrumbs-size
src/components/OcBreadcrumb.vue

We've increased the font size of breadcrumbs to match the one from `oc-table` items.

feat: increase breadcrumbs font size

---

changelog/unreleased/enhancement-table-padding
src/components/table/OcTable.vue
src/components/table/OcTableFiles.vue
src/components/table/__snapshots__/OcTable.spec.js.snap
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

We've added new prop called `paddingX` which can be used to set the padding along x axis of the `oc-table` or `oc-table-files`.

feat: add paddingX prop

---

changelog/unreleased/enhancement-aria-hide-images
src/components/OcImage.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

When the `alt` property of the oc-image is empty we now set `aria-hidden="true"`.

Aria-hide images without alt tags

---

changelog/unreleased/bugfix-router-link-href-overwitten-by-empty-href-property
src/components/OcButton.vue
src/components/table/__snapshots__/OcTableFiles.spec.js.snap

While setting the type property to 'router-link' the empty href property will overwrite the href target with null.
This means that the router link still works but the correct target is not set in the < a > element.

Move href into extra computed properties

---

changelog/unreleased/enhancement-oc-drop
package.json
src/components/OcDrop.spec.js
src/components/OcDrop.vue
src/components/__snapshots__/OcBreadcrumb.spec.js.snap
src/components/__snapshots__/OcDrop.spec.js.snap
src/directives/OcTooltip.js
src/utils/logger.js
yarn.lock

this pr replaces uk-drop by using tippy (same as tooltip directive).
The oc-drop api was kept intact so no changes by the consuming app expect importing tippy as peer dependency should be required.
It also keeps care that a11y (accessibility) usage of the web-ui is fulfilled.
Because it's not a breaking change it can be part of the upcoming 6.4.0 release.

replace uk-drop by using tippy

---

changelog/unreleased/enhancement-remove-notification-close-button
changelog/unreleased/enhancement-show-notification-close-button-via-property
src/components/OCNotificationMessage.vue
src/components/OCNotifications.vue

Notifications will now automatically close after a certain amount of time which can be defined via property. Also fixed some links in the docs in addition to that.
Small improvements in the course of this:
* fixed some links in the docs
* removed prefixes from properties

Remove close button on notifications

---

changelog/unreleased/enhancement-oc-select-a11y 
src/components/OcSelect.vue

This PR addresses to issues:
1. Adding a default No options available slot, which appears if there are no items passed to the component or the while type in a search query without a result. This text will also be synced to transifex.
2. Unfortunately there is an aria label in the combo box with the text: "Search for option" which can't be replaced via the vue-select API, in order to sync the text to transifex we need to replace it.

Added l10n no options text, added translation for vue-select combobox aria-label

---

changelog/unreleased/enhancement-themable-tr-height
src/components/table/OcTable.vue
src/components/table/OcTableFiles.vue
src/components/table/__snapshots__/OcTable.spec.js.snap
src/components/table/__snapshots__/OcTableFiles.spec.js.snap
src/tokens/ods/size.yaml

First idea was to use existing padding/margin classes, however they don't properly work in table rows plus re-using the generic spacing classes to configure a more dense/lofty table row will yield unwanted results in the rest of the UI so I went for introducing a dedicated table row height CSS variable

Move tr height from prop to token

---

changelog/unreleased/enhancement-active-nav
src/components/OcSidebarNavItem.vue

This PR switches background color for nav items in `hover` and `active` state within the `OcSidebarNav` component, now fulfilling required color contrasts for WCAG 2.1 AA.
Up for discussion if white is too heavy.

Change OcSidebarNav active and hover colors

---

changelog/unreleased/enhancement-active-nav
src/components/OcSidebarNavItem.vue

This PR removes the background color transition in the sidebar nav items, since it turned out to be too heavy now with high contrast colors.

Remove background color transition in sidebar nav

---

changelog/unreleased/enhancement-a11y-color-contrasts
src/components/OcButton.vue

This PR fixes that icons in OcButtons were not flipped to the inverse text color on hover. Again, the color transition was too harsh with high contrast, so I removed it.

Fix hover svg fill in OcButton

---

changelog/unreleased/enhancement-reduce-fileslist-row-height
src/components/table/_OcTableCell.vue
src/tokens/ods/size.yaml

issue: https://github.com/owncloud/web/issues/5078
**problem:** row height is limited by the sharing indicators.
this PR sets the row height to the minimum possible with the sharing-indicators still placed below the filename. it is meant as a quickfix to reduce the filelist-height.
please review carefully, newbie PR :-)

reduce fileslist row height

---

changelog/unreleased/enhancement-text-input-clear
src/components/OcTextInput.spec.js
src/components/OcTextInput.vue
src/components/__snapshots__/OcModal.spec.js.snap

Adding an optional clear button to the OcTextInput component. It has a default aria-label (`Clear input`) which can be overridden via a prop. Button can be reached via keyboard navigation and used via `ENTER` key or via click. Using the button clears the text input and emits an `input` event with an empty string.

Text input clear

---

changelog/unreleased/bugfix-tippy-non-interactive
src/directives/OcTooltip.js

Disabling interactivity in tooltips.
Fixes https://github.com/owncloud/owncloud-design-system/issues/1321

Disable interactive prop in tippy

---

.drone.star
.gitignore

Disabled the built-in clone step of drone. Provide out own clone step that just checks out the commit from the PR and does not do any merge-forward to tip of master. That should help SonarCloud to match up the analysis based on a commit ID that matches the commit ID in the PR/branch on GitHub.
This applies code similar to https://github.com/owncloud/web/pull/5223
CI

[tests-only] Add custom clone step

---

changelog/unreleased/enhancement-logo-sizing
src/components/OcLogo.vue
src/tokens/ods/size.yaml

We've added theming variables for the max-width and max-height of the OcLogo component and increased the default (max-)height.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/795
This will change the sidebar in ownCloud Web from this:
to this:

Add max-width and max-height vars for OcLogo and increase defaults

---

changelog/unreleased/bugfix-sticky-appsidebar-header
src/components/OcAppSideBar.vue

Make OcAppSideBar header sticky
- Fixes a ticket in `web` (and will need test selector updates there 😈  )
See changelog item

Make OcAppSideBar header sticky & cleanup component

---

changelog/unreleased/enhancement-add-breakpoints-to-theming-init
src/system.js
src/system.spec.js

Technically a bugfix but since we haven't communicated the theme-ability of breakpoints it can count as a feature 👹 
We have breakpoint CSS props and the ability to set custom CSS props via theming but were missing out on initializing (possibly present) breakpoint variables from a theming config passed by a ODS user

Add breakpoints to theming initialization

---

jest.conf.js
sonar-project.properties

spec files don't need to be covered in tests 
part of https://github.com/owncloud/web/issues/5234
correct coverage report
look at sonarcloud output

[tests-only] don't count spec files into the coverage

---

changelog/unreleased/bugfix-pagination-unnecessary-skip
src/components/pagination/OcPagination.spec.js
src/components/pagination/OcPagination.vue

In cases where the pagination should only render 4 pages at once
and 4 are available, it rendered a skip label `< 1 2 ... 4 >` even if it's not required.
Now this is fixed and it renders `< 1 2 3 4 >` instead.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1404
the pagination should render the pool of available items correctly
local installation

ocPagination skip label bugfix

---

changelog/unreleased/bugfix-icon-update
src/components/OcIcon.spec.js
src/components/OcIcon.vue

Updating `oc-icon` name prop crashed `vue-inline-svg`.
We had to overwrite `vue-inline-svg` download method and forgot to implement its `isPending`
property on the returned promise.
- Fixes #1405
be able to update icons
- local installation with setTimeout

fix oc-icon name update error

---

changelog/unreleased/bugfix-show-dashes-when-negative-filesize-given
src/components/resource/OcResourceSize.spec.js
src/components/resource/OcResourceSize.vue
src/components/table/OcTableFiles.spec.js

1. use toEqual to assert content, because `toMatch` is expecting a regex, to `toMatch("")` would always be true, I noticed it after I changed the code and the test still passed
2. as discussed in #1402 show negative number as `--` and not empty string
unit tests

show '--' for negative file size

---

src/components/OcAppSideBar.spec.js
src/components/OcAppSideBar.vue

Added unit tests for `OcAppSideBar`
- sidebar title
✓ should set the provided heading text from prop
- sidebar slots
✓ should content HTML from content slot title
✓ should content HTML from content slot content
✓ should content HTML from content slot footer
✓ should content HTML from content slot action
- default action
✓ should set the provided close button label
✓ should emit close when the action button is clicked
- Part of #1366  
- 🤖

[unit-tests] Added unit tests for oc app sidebar

---

src/components/OcButton.spec.js

tests if
- button emits click event on click
- button is not clickable while disabled
- button can show provided slot
- https://github.com/owncloud/web/issues/5217
- #1366 
- :robot:

[tests-only] Added unit tests for oc button

---

changelog/unreleased/enhancement-modal-initial-focus
src/components/OcModal.vue
src/components/__snapshots__/OcModal.spec.js.snap

The OcModal component sets the initial focus to the input element now, if one exists. If the input element doesn't exist the focus remains on the modal itself, like we had it before.
- Fixes https://github.com/owncloud/web/issues/3684
Improve UX

Handle initial focus in OcModal

---

src/components/table/OcTableFilesSort.spec.js

Ran into some troubles with dynamically generated timestamps, reduced them with strings. Also removed unused date properties since testing one (`mdate`) should be enough

Remove unused props, reduce flakyness

---

src/components/OcAutocomplete.spec.js

added unit test for `OcAutocomplete` component
- only covered message part
- dropdown test will be added after UiKit removal
- 🤖

added unit tests for OcAutocomplete component

---

src/assets/icons/comment.svg

Add `comment` icon to icon assets
Coming from google material design. License is apache 2.0, so no attribution is required.
https://fonts.google.com/icons?selected=Material+Icons:mode_comment

Add `comment` icon

---

src/components/pagination/OcPagination.spec.js

- selectors are reused
- wrapper is created from a single source
- unit tests optimizations
- :robot:

Reuse selectors variables and wrapper function inside pagination spec file

---

changelog/unreleased/bugfix-current-breadcrumb-hover
src/components/OcBreadcrumb.vue

See changelog item
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1416
- Manually

No hover on current page's breadcrumb item

---

changelog/unreleased/enhancement-textarea-configurable-enter-linebreak
changelog/unreleased/feature-textarea-configurable-enter-linebreak
src/components/OcTextarea.spec.js
src/components/OcTextarea.vue

#1422 Textarea enable linebreak (submitOnEnter)

---

changelog/unreleased/bugfix-tablefiles-id
src/components/table/OcTableFiles.vue

Regex was wrong and actually unnecessary so it can be removed. Needs to be published for integration in `web`.

Fix resource ID handling in OcTableFiles contextmenu

---

changelog/unreleased/bugfix-tablefiles-id
src/components/table/OcTableFiles.spec.js
src/components/table/OcTableFiles.vue

Regex for cleaning up the resource ids being used in the template of OcTableFiles was not greedy (my bad). Fixing it with this PR.
Additionally this PR
- groups unit tests of OcTableFiles so that reading the spec file is (hopefully) easier
- changes html ids to `context-menu` instead of `quick-action`, which IMO is more precise
- changes the aria-label `Show quick actions` to `Show context menu`
- added a unit test

Fix replace regex for ids in template of OcTableFiles

---

changelog/unreleased/bugfix-button-inline-flex
src/components/OcButton.vue

Our OcButton had `display: flex` which basically made it a block element and destroyed alignment of buttons inside containers. This PR changes it to `display: inline-flex` which makes it an inline element again (default display of a button is `inline-block`).
For review: please build locally and test in ownCloud Web with a local link.

Make OcButton inline

---

changelog/unreleased/enhancement-oc-drop-remove-aria-describeby
src/components/OcDrop.vue
src/components/__snapshots__/OcDrop.spec.js.snap

See https://github.com/owncloud/web/issues/5398
- Fixes https://github.com/owncloud/web/issues/5398

Remove aria-described-by in tippy for a11y reasons

---

build/webpack.system.conf.js
changelog/unreleased/change-drop-deprecated-components
changelog/unreleased/change-production-bundle-content

Omit example imgs & docs.scss from prod bundle

---

changelog/8.3.1_2021-08-04/bugfix-context-menu-events
package.json
sonar-project.properties
src/components/table/OcTableFiles.vue

This PR fixes that a click on a context menu item in OcTableFiles also emitted an unnecessary `showDetails` event.

Fix unnecessary showDetails event in OcTableFiles

---

changelog/unreleased/bugfix-selected-files-drag-drop
src/components/table/OcTableFiles.vue

Bugfix: Drag & Drop doesn't select files correctly

---

changelog/unreleased/change-enable-multiple-highlighting
src/components/table/OcTableFiles.spec.js
src/components/table/OcTableFiles.vue

See https://github.com/owncloud/web/issues/5164

Web-648: OcTableFiles enable multiple highlighting using selection

---

changelog/unreleased/enhancement-group-files-folders-when-sorting-by-name
src/components/table/OcTableFiles.vue
src/components/table/OcTableFilesSort.spec.js
src/components/table/mixins/sort.js

See https://github.com/owncloud/web/issues/5613

Web-853: Group files and folder when sorting by name

---

changelog/unreleased/bugfix-contextmenu-change-selection-model
src/components/OcStatusIndicators.vue
src/components/table/OcTable.vue
src/components/table/OcTableFiles.vue

We changed the rightclick logic so the selection model changes to the file the rightclick was performed on.

Change selection model on rightclick

---

changelog/unreleased/change-downgrade-sass-version
package.json
yarn.lock

I'm upgrading our version of owncloud/web to use v9.0.0 of the owncloud-design-system and there are many deprecation warnings in ui-kit, any thoughts on this? Downgrading to sass v1.32.12 removes the warnings and makes it easier to digest the console log and any actual errors that may occur.
```
⠼ Building Design System...DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($global-gutter, 2)
247 │ $card-header-padding-vertical: round($global-gutter / 2) !default;
│                                      ^^^^^^^^^^^^^^^^^^
╵
node_modules/uikit/src/scss/variables-theme.scss 247:38  @import
src/styles/styles.scss 187:9                             root stylesheet```
Built with `yarn build:system` and compared binaries, there …

Downgrade sass version to avoid deprecation errors from ui-kit

---

changelog/unreleased/bugfix-default-sort-by
changelog/unreleased/bugfix-sort-by-date
src/components/table/OcTable.sort.spec.js
src/components/table/OcTableFiles.vue
src/components/table/OcTableFilesSort.spec.js
src/components/table/mixins/sort.js

This PR
- enforces an initial `sort-by` value, which gets computed from the first sortable field in the list of fields in `OcTableFiles`
- fixes sorting by dates by not comparing relative dates anymore, but comparing unix timestamps instead.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/1552
- Works towards https://github.com/owncloud/web/issues/5614
- Works towards https://github.com/owncloud/web/issues/5490
Improve UX
- added/adapted unit tests

Fix sorting behaviour

---

changelog/9.1.0_2021-08-17/enhancement-add-sidebar-toggle-icons
src/assets/icons/arrow_back.svg
src/assets/icons/arrow_forward.svg
src/assets/icons/chevron_double_down.svg
src/assets/icons/chevron_double_left.svg
src/assets/icons/chevron_double_right.svg
src/assets/icons/chevron_double_up.svg
src/assets/icons/chevron_down.svg
src/assets/icons/chevron_left.svg
src/assets/icons/chevron_up.svg

Deleted the arrow icons, since they were kind of duplicating the `chevron` icons that we already have. Made the chevron icon set more complete by adding `top` and `bottom` directions for single chevrons and adding all directions for double chevrons. See screenshot below.

Fix chevron icons

---

src/components/OcDrop.vue

drop example used undefined $_ocDrop_show method, update to use only
show

fix(ocDrop bugfix): update buggy drop example

---

changelog/unreleased/bugfix-use-pointer-cursor-for-ocselect-actions
src/components/OcSelect.vue

I changed the cursor for the actions (usually the down/up arrows) on `OcSelect` to `default`.
- Fixes https://github.com/owncloud/customer_portal/issues/1067
Currently a `text` cursor is shown for the down/up arrows in `OcSelect` which is confusing because clicking it does not trigger a text edit but expands/collapses the drop down menu.
Alternatively a `pointer` cursor (like for the "clear-X") could be used. My chromium on Linux uses `default` for regular `<select>` tags fwiw.
I can add a changelog entry if you otherwise approve this PR.
- checked in generated documentation :) 
before:
after:

Use pointer cursor for OcSelect actions

---

changelog/unreleased/fix-search-for-options-provided-as-objects
src/components/OcSelect.vue
src/components/table/OcTableFiles.spec.js

I made `OcSelect.filter`make use of the `label` prop as the original filter function of vue-select also does, i.e. this is a regression fix for a breaking change introduced in https://github.com/owncloud/owncloud-design-system/pull/1521
This fixes broken search in ownBrander 2.0.

[OcSelect] Fix search for options provided as objects

---

changelog/unreleased/change-pagination-page-param
changelog/unreleased/enhancement-pagination-page-param
src/components/pagination/OcPagination.spec.js
src/components/pagination/OcPagination.vue

instead of having current pagination page as param refactor it to
use the query route object
BREAKING CHANGE: this could break in some cases where the implementing
logic relies on route page param, to fix switch to use route query
object

refactor(pagination): use route query object instead of param

---

changelog/unreleased/bugfix-reset-droptarget-background
src/components/OcSelect.vue
src/components/table/OcTable.vue

Thanks @paulcod3 for the hint, wasn't visible in the ODS but got discovered once the `EVENT_FILE_DROPPED` actually did something inside `web`

Reset row background on dragDrop event in OcTable

---

changelog/unreleased/change-ocselect-label
changelog/unreleased/enhancement-ocselect-label
src/components/OcSelect.vue

Ported #1570 to master.
- Fixes #1503
- test case 1:
- test case 2:
- ...

Add label to OcSelect  (port to master)

---

changelog/unreleased/change-ocselect-label
changelog/unreleased/enhancement-ocselect-label
src/components/OcSelect.vue

Add label to OcSelect

---

changelog/unreleased/change-refactor-oc-avatars
src/components/avatars/OcAvatarFederated.vue
src/components/avatars/OcAvatarGroup.vue
src/components/avatars/OcAvatarGuest.vue
src/components/avatars/OcAvatarLink.vue
src/components/avatars/OcAvatars.vue
src/components/avatars/__snapshots__/OcAvatars.spec.js.snap
src/components/table/OcTableFiles.vue

Make accessible description on OcAvatars optional
Also fixed imports of the OcAvatarItem in more specific items on the way.

Make accessible description on OcAvatars optional

---

changelog/unreleased/bugfix-prevent-hover-style-on-oc-table-footer
src/components/table/OcTable.vue

This fix is to prevent the <tfooter> element from receiving the hover style (when rendering a `<oc-table>` component with `hover="true"` as it makes it appear as another row in the table which isn't accurate and probably not good for accessibility.  Typically at the bottom there are totals about the size of the files / folders used.
**Before**
**After**
Makes the table interface cleaner (especially when there are only a few files / folders) - makes it not seem broken (eg. is there a hidden file or folder?) and correctly separates any data or table summary info in the footer from the main row content.
Tested in Chrome and IE (edge) browsers and works as expected.

fix: prevent hover style on footer of <oc-table>

---

changelog/unreleased/enhancement-octextinput-props
src/components/molecules/OcTextInput/OcTextInput.spec.js
src/components/molecules/OcTextInput/OcTextInput.vue

1) Fixed the clear button being visible even when element is disabled
2) Made clear button emit `null` instead of empty string
3) Made input/change event handling a bit more consistent
4) Added `defaultValue` prop that is for now passed as `placeholder` to the input field. 
Needs UX concept by @kulmann and @tbsbdr
- Fixes one :x: from #1350 (`defaultValue`) and makes it more consistent with other components that also emit `null` on clear (which is not part of that table)
Same as #1634 and #1635 
Instead of using native `placeholder` prop on the `input` element, I would propose to introduce the `defaultValue` property which for now uses `placeholder` but keeps that as implementation detail. That way I can already use the functionality in ownBrander 2.0 and will automatically benefit from a …

OcTextInput: add defaultValue prop and make clear button null the value

---

changelog/unreleased/bugfix-notification-word-break
src/components/molecules/OcNotificationMessage/OcNotificationMessage.vue

Supersedes #1736 (wrong branch name & changelog item)
The OcNotificationMessage code & styling seems a bit messy in its current state, but we can probably address this when implementing the new screendesigns. This is a simple fix for a UI glitch in `web`
- Fixes #1712

Add word-break rule to OcNotificationMessage

---

changelog/unreleased/enhancement-add-drag-drop-ghost
src/components/molecules/OcTable/GhostElement/GhostElement.vue
src/components/molecules/OcTable/OcTable.vue
src/components/templates/OcTableFiles/OcTableFiles.vue

See https://github.com/owncloud/web/issues/5788

 Add Ghost Element for Drag & Drop move

---

changelog/unreleased/enhancement-breadcrumb-contextmenu
src/components/molecules/OcBreadcrumb/OcBreadcrumb.spec.js
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap

- Works towards https://github.com/owncloud/web/issues/6030
- Manually

Add breadcrumb contextmenu

---

changelog/unreleased/enhancement-drop-padding-size
src/components/atoms/OcDrop/OcDrop.spec.js
src/components/atoms/OcDrop/OcDrop.vue
src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
src/components/templates/OcTableFiles/OcTableFiles.vue
src/utils/sizeClasses.js

We've added a `paddingSize` property to the OcDrop component for specifying a dedicated padding of the div that wraps the content slot. It defaults to "medium" and also allows to remove the padding entirely.
Being able to remove the padding of an OcDrop where it's not needed / ugly (e.g. role selection for shares in web).
- added unit tests for padding size to class transformation

Add padding size for OcDrop

---

changelog/unreleased/enhancement-truncate-file-names
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/atoms/OcResourceName/__snapshots__/OcResourceName.spec.js.snap
src/components/organisms/OcResource/OcResource.vue

- https://github.com/owncloud/owncloud-design-system/issues/1758
- https://jira.owncloud.com/browse/WEB-1026

Truncate file names while preserving file extensions

---

changelog/unreleased/bugfix-language-formatted-dates
src/components/templates/OcTableFiles/OcTableFiles.vue

Now setting the language when formatting dates, so that localized parts of the date/time get shown according to the respective language.
Correct localization

Set current language for formatted dates

---

changelog/11.3.1_2021-12-03/bugfix-breadcrumb-contextmenu-padding
package.json
sonar-project.properties
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue

Removes the padding from the context menu in the breadcrumbs to align its visual appearance with the context menu in the files table. Also bumping the version number for an immediate bugfix release.

Remove padding from breadcrumb context menu

---

changelog/unreleased/change-remove-unused-props
src/components/atoms/OcButton/OcButton.spec.js
src/components/atoms/OcButton/OcButton.vue
src/components/atoms/OcIcon/OcIcon.vue
src/components/molecules/OcTextInput/OcTextInput.spec.js
src/components/molecules/OcTextInput/OcTextInput.vue
src/components/organisms/OcModal/OcModal.vue

Found some small chances for improvement in ODS...

Minor code style and docs improvements

---

src/components/atoms/OcButton/OcButton.spec.js
src/components/atoms/OcGrid/OcGrid.spec.js
src/components/atoms/OcImage/OcImage.spec.js
src/components/atoms/OcNotifications/OcNotifications.spec.js
src/components/molecules/OcNotificationMessage/OcNotificationMessage.spec.js
src/components/molecules/OcTextInput/OcTextInput.spec.js

To assert the errors thrown, basic `try & catch` implementation was done before.
But this can be replaced using `toThrow` fn from `expect` where we can assert the expected error message thrown.
makes the test code look far better.
- locally
- :robot:

[tests-only] refactored try catch use cases inside unit tests

---

changelog/unreleased/change-externalize-oc-table-sorting
src/components/molecules/OcTable/OcTable.sort.spec.js
src/components/molecules/OcTable/OcTable.vue
src/mixins/sort.js

The sorting depends on the structure of resources which do not exist in ODS but only in web-app-files.
Moreover, we need to sort before pagination and as pagination is not handled in `OcTable` either, we need to handle sorting externally as well.
This has the additional benefit that this prepares us better for retrieving server sorted and paginated resources.
This is a draft and as such has a few rough edges.
For instance sorting has been added to the first example of `OcTable`, should we get this close to merging this would deserve its own section obviously :) 
- test case 1:
- test case 2:
- ...

Extract sort handling from OcTable

---

changelog/unreleased/change-externalize-oc-table-sorting
src/components/molecules/OcTable/OcTable.sort.spec.js
src/mixins/sort.js

Allow a sort direction default coming from the field definition instead of just assuming it. This is important because the default sort direction for the `name` column (`ASC`)  is different from the default sort direction for the `mdate` column (`DESC`). We have no way of assuming this. Should be provided instead.
This is considered a continuation of https://github.com/owncloud/owncloud-design-system/pull/1825 so no additional changelog item provided.

Allow sort direction defaults from field

---

changelog/unreleased/change-remove-implicit-registration
changelog/unreleased/enhancement-add-composition-api
changelog/unreleased/enhancement-lazy-table-cells
docs/docs.helper.js
package.json
src/components/atoms/_OcTableCellData/_OcTableCellData.vue
src/components/molecules/OcTable/OcTable.spec.js
src/components/molecules/OcTable/OcTable.vue
src/composables/index.js
src/composables/useIsVisible/index.js
src/composables/useIsVisible/index.spec.js
src/system.js
yarn.lock

primary change int this pr is the introduction of lazy table cells, on top we've removed the implicit ODS registration for the global VUE instance and made the vue composition-api available.
to get a detailed overview of what changed please read the individual changelogs.
Please wait for the `new Design` related PR's before merging to master
- Fixes https://github.com/owncloud/web/issues/6046
be able to render larger amount of table data 
- unit-tests
- manual-tests

Lazy table cells

---

changelog/unreleased/change-use-remixicons
docs/components/status/Components.vue
src/components/atoms/OcAvatarItem/OcAvatarItem.vue
src/components/atoms/OcButton/OcButton.vue
src/components/atoms/OcGrid/OcGrid.vue
src/components/atoms/OcTag/OcTag.vue
src/components/molecules/OcAccordionItem/OcAccordionItem.vue
src/components/molecules/OcAlert/OcAlert.vue
src/components/molecules/OcAvatarFederated/OcAvatarFederated.vue
src/components/molecules/OcAvatarGuest/OcAvatarGuest.vue
src/components/molecules/OcAvatarLink/OcAvatarLink.vue
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
src/components/molecules/OcNotificationMessage/OcNotificationMessage.vue
src/components/molecules/OcPagination/OcPagination.vue
src/components/molecules/OcStatusIndicators/OcStatusIndicators.vue
src/components/molecules/OcTable/OcTable.vue

Some components got overlooked when changing the iconset used in the ODS
- Component ready-ness table
- Avatar icons for federated, link & guest shares
- Small other icon usages in components and usage examples

Fix icon usage after switch to Remix icons

---

changelog/unreleased/enhancement-sizes
src/tokens/ods/space.yaml

This PR changes margins and paddings to be multiples of 8 instead of 10. Personal wish from @tbsbdr 😇

Use multiples of 8 instead of 10 for margins and paddings

---

changelog/unreleased/bugfix-tooltip-reactivity
src/directives/OcTooltip.js

We've fixed an issue with the OcTooltip when the tooltip
gets hidden by reactivity and then reactivated with some value.

Bugfix OcTooltip reactivity after beeing destroyed

---

changelog/unreleased/enhancement-parent-folder-distinguish-files
src/components/organisms/OcResource/OcResource.vue

Stop click propagation on parent folder clicks in OcResource. This is needed because otherwise the click handler of the parent fires as well (if it has one).

Stop click propagation on parent folder clicks in OcResource

---

src/components/OcSidebarNav.spec.js
src/components/OcSidebarNav.vue

Replaced `header` element in sidebar navigation with `figure` element in order to avoid having two `header` elements on the same page.
- Works towards https://github.com/owncloud/web/issues/5391
- Dev tools
- WAVE browser extension

A11y fix skip areas

---

src/components/__snapshots__/OcModal.spec.js.snap
src/tokens/ods/color.yaml

Changed the border color for inputs and checkboxes so it has a contrast ratio of at least 3:1. New contrast ratio is now 7.01:1.
- Works towards https://github.com/owncloud/web/issues/5386
- Used this contrast checker to determine the right color: https://webaim.org/resources/contrastchecker/
**Page 1 (Alle Dateien)**
When creating a public link in the case the user doesn’t fill the fields a error message appears above the form. This error message has a „X“ button on the right (to remove the message). Here the contrast ration to the background color is lower than 3:1.
Not able to reproduce this scenario, as there is no error message being displayed. Instead the submit button is just disabled as long the required input field is empty.

A11y fix sufficient contrast

---

changelog/unreleased/enhancement-redesign-filetype-icons
src/components/atoms/OcResourceIcon/OcResourceIcon.vue
src/components/organisms/OcResource/OcResource.spec.js

Enforce the heights of folder- and document-resource-icons to be the same so that document type icons don't have a larger appearance anymore.

Fix document type icon heights in relation to folder icon

---

changelog/unreleased/change-pass-folder-link-to-oc-resource-component
package.json
src/components/organisms/OcResource/OcResource.spec.js
src/components/organisms/OcResource/OcResource.vue

Change: Pass folderLink to OcResource component
For more flexibility, the folderLink needs to be passed to the OcResource component
- test case 1:
- test case 2:
- ...

Pass folderLink to OCResource component

---

changelog/unreleased/bugfix-oc-drop-shadow
src/components/atoms/OcDrop/OcDrop.vue
src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
src/styles/theme/helper.scss

Changes the drop shadow to emulate a light source from the top left. Fix sharp edges without box shadow around the rounded corners of the drop (class name was wrong, `oc-drop-rounded` instead of `oc-rounded`). Also removed a hardcoded box shadow that was overwriting the box shadow class.

Fix drop shadow in OcDrop

---

src/components/atoms/OcAvatarItem/OcAvatarItem.vue
src/components/atoms/OcList/OcList.vue
src/components/atoms/OcResourceIcon/OcResourceIcon.vue
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/atoms/OcResourceSize/OcResourceSize.vue
src/components/atoms/_OcGhostElement/_OcGhostElement.vue
src/components/molecules/OcAvatarFederated/OcAvatarFederated.vue
src/components/molecules/OcAvatarGroup/OcAvatarGroup.vue
src/components/molecules/OcAvatarGuest/OcAvatarGuest.vue
src/components/molecules/OcLogo/OcLogo.vue

Some components on https://owncloud.design/ are being listed as either `In review` or with missing release info. This PR fixes it (couldn't find all the relevant release info for e.g. OcList though)

Clean up component release info

---

changelog/unreleased/bugfix-background-primary-gradient-border
src/styles/theme/background.scss

Fixes some ~1px difference when using `.oc-background-primary-gradient`
See changelog

Fix background-gradient border problem

---

changelog/unreleased/enhancement-card-background-color
src/styles/theme/oc-card.scss

We've adjusted he background color to oc-card to have an outstanding look
Before:
After:
- test case 1:
- test case 2:
- ...

Apply outstanding background color to oc-card

---

changelog/unreleased/enhancement-modal-focus-trap
src/components/organisms/OcModal/OcModal.vue
src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap

* add modal option to define which child element should be focused initially
- https://github.com/owncloud/web/pull/6410

extend modal focus-trap

---

changelog/unreleased/bugfix-modal-initial-focus
src/components/organisms/OcModal/OcModal.vue

Bugfix: Initial focus in OcModal
We've fixed a bug that was introduced in the last version, where the initial focus element provided via the focusTrapInitial property was broken.
- test case 1:
- test case 2:
- ...

Fix initial focus trap

---

changelog/unreleased/change-ocbutton-default-type
src/components/atoms/OcButton/OcButton.vue
src/components/molecules/OcAlert/__snapshots__/OcAlert.spec.js.snap
src/components/molecules/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap

This changes the default type of `OcButton` to `button`.
The default type for `<button>` elements is `submit`. As we use it all over the place now for a11y reasons, we have lots and lots of submit buttons everywhere, which is most likely not what we want.
Could not find an open ticket for this issue.
I recently noticed that pressing enter in one of the text inputs in the public link editing view opened the datepicker instead of saving the link:
https://user-images.githubusercontent.com/448487/157119392-20d2e849-3124-408f-a4e6-88af05878c40.mp4
It was @fschade  (💖 ) who pointed me towards the root of the issue:
pressing enter submits the form, which automatically clicks the first (at least in chromium) button which is not of type "button". In this case this happened to be the button that …

OcButton: Change default type of buttons to button

---

changelog/unreleased/enhanchement-oc-tag-size
src/components/atoms/OcTag/OcTag.vue
src/components/atoms/OcTag/__snapshots__/OcTag.spec.js.snap

- test case 1:
- test case 2:
- ...

Added size property to oc-tag

---

changelog/unreleased/enhancement-polish-oc-switch
src/components/atoms/OcSwitch/OcSwitch.vue

See https://github.com/owncloud/web/issues/6492

Polish OcSwitch

---

CHANGELOG.md
changelog/unreleased/enhancement-underline-resource-name
src/components/atoms/OcButton/OcButton.vue
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/atoms/OcSearchBar/OcSearchBar.vue
src/components/atoms/OcTextarea/OcTextarea.vue
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
src/components/molecules/OcTable/OcTable.vue
src/components/molecules/OcTextInput/OcTextInput.vue
yarn.lock

See https://github.com/owncloud/web/issues/6492
and https://github.com/owncloud/web/pull/6584

Sprint 16 design fixes

---

changelog/unreleased/enhancement-redesign-status-indicators
src/components/molecules/OcStatusIndicators/OcStatusIndicators.vue

Recent changes to OcButton styling affected the OcStatusIndicator border-radius. It's now back to a "full circle"

Make StatusIndicators properly round again

---

changelog/unreleased/enhancement-configurable-resource-parentfolder
src/components/organisms/OcResource/OcResource.spec.js
src/components/organisms/OcResource/OcResource.vue
src/components/organisms/OcResource/__snapshots__/OcResource.spec.js.snap

Makes default parent folder name configurable for `web` to differentiate between "All files" (former fallback, needed for OC10) and "Personal/{spaceName}" in oCIS

Ad OcResource parentfolder name prop

---

changelog/unreleased/enhancement-primary-button-gradient
src/components/atoms/OcButton/OcButton.vue

After using #2036 in `web`, it became apparent that the color/icon/border color of the (gradient-filled) primary button wasn't applied correctly in dark mode

Update gradient button text&border&icon color

---

changelog/unreleased/bugfix-darkmode-disabled-textarea
src/components/atoms/OcTextarea/OcTextarea.vue
src/styles/theme/oc-form.scss

Not perfect, we'll need to look into unifying the form components sometime soon
- Fixes #2053
Here's how enabled/disabled OcTextarea and OcTextInput look like:

Improve disabled textarea contrast in darkmode

---

changelog/unreleased/enhancement-oc-resource-is-file-extension-displayed
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/organisms/OcResource/OcResource.vue

Enhancement: Add `isFileExtensionDisplayed` property
We've added the `isFileExtensionDisplayed` property to the `ocResource` component,
to determine whether the file extension should be displayed or not.
- Part of https://github.com/owncloud/web/issues/6730
- test case 1:
- test case 2:
- ...

Oc resource show file extension

---

changelog/unreleased/enhancement-add-contextual-helper-component
src/components/atoms/OcButton/OcButton.vue
src/components/atoms/OcContextualHelper/OcContextualHelper.spec.js
src/components/atoms/OcContextualHelper/OcContextualHelper.vue
src/tokens/ods/font.yaml

See https://github.com/owncloud/web/issues/6590
- Works towards [<issue_link>](https://github.com/owncloud/web/issues/6590)

Create OcContextualHelper component

---

changelog/unreleased/bugfix-text-color-buttons-avatars-in-hovered-rows
src/components/molecules/OcTable/OcTable.vue

- Prevent hover span color from applying to buttons and avatars
- Fixes #2138
Improve the contrast
Before and after

Fix text color of buttons and avatars in hovered table rows

---

changelog/unreleased/bugfix-tooltip-break-word
src/components/atoms/OcDrop/OcDrop.vue
src/styles/styles.scss
src/styles/theme/tooltip.scss

This PR fixes long words or paths breaking the tooltips in the sidebar:
By adding a `word-wrap: break-word` to the tippy content.
This along with ellipsizing the paths will remove the scrollbar from the sidebar.

Fix tooltips overflowing on long words

---

changelog/unreleased/bugfix-modal-input-enter-submission
src/components/organisms/OcModal/OcModal.vue

This surfaces in https://github.com/owncloud/web/pull/6961 where using the enter key upon password modification would continue in the code but not close the modal (while clicking the confirm button did both). Please link this PR locally with the mentioned `web` PR for testing

Align submit-via-enter for OcModal input with submit button

---

changelog/unreleased/enhancement-resource-name-no-truncate
src/components/atoms/OcResourceName/OcResourceName.spec.js
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/atoms/OcResourceName/__snapshots__/OcResourceName.spec.js.snap
src/components/organisms/OcResource/__snapshots__/OcResource.spec.js.snap
src/styles/theme/oc-text.scss

Groundwork for https://github.com/owncloud/web/issues/6776

Add option to the resourceName component to prohibit the name truncation

---

changelog/unreleased/enhancement-resource-name-html-title
src/components/atoms/OcResourceName/OcResourceName.spec.js
src/components/atoms/OcResourceName/OcResourceName.vue
src/components/atoms/OcResourceName/__snapshots__/OcResourceName.spec.js.snap

We've added the HTML title attribute to the resourceName component in case no tooltip is being displayed.
- Part of https://github.com/owncloud/web/issues/6776

Add HTML title to the resourceName component

---

changelog/unreleased/enhancement-modal-add-checkbox-secondary-button
src/components/atoms/OcDatepicker/OcDatepicker.vue
src/components/atoms/OcResourceLink/OcResourceLink.vue
src/components/organisms/OcModal/OcModal.vue
src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap

We've added an optional checkbox and secondary button to the OcModal
- Fixes https://github.com/owncloud/web/issues/6996

OcModal: Add checkbox and secondary button

---

changelog/unreleased/enhancement-hover-in-oc-drop-menues
src/components/atoms/OcDrop/OcDrop.vue
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue
src/components/molecules/OcTable/OcTable.vue

- moving hover effect for tippy-box implemented in web to ods: adding hovers on "New" menus
- unifying spacings for tippy-box menus
- web part: https://github.com/owncloud/web/pull/6762
Fixes hover menus issues from https://github.com/owncloud/web/issues/6555
More consistency in style of different menus:

Style fixes for menus

---

changelog/unreleased/enhancement-progress-bar-indeterminate-state
src/components/atoms/OcProgress/OcProgress.vue
src/components/atoms/OcProgress/__snapshots__/OcProgress.spec.js.snap
src/vuetify.js

We've added an indeterminate state to the progress bar.
I've decided to build the indeterminate state myself (okay, with quite some help from StackOverflow :D) because the integration of Vuetify is a bit more complex than I anticipated. We can still do this later if neccessary.
Needed for https://github.com/owncloud/web/issues/7105

Implement an indeterminate state for the progress bar

---

changelog/unreleased/change-table-emit-event-row-click
changelog/unreleased/enhancement-checkbox-add-outline
src/components/atoms/OcCheckbox/OcCheckbox.spec.js
src/components/atoms/OcCheckbox/OcCheckbox.vue
src/components/molecules/OcTable/OcTable.vue

See https://github.com/owncloud/web/issues/6029
- Works towards https://github.com/owncloud/web/issues/6029

Add OcCheckbox outline option, OcTable add event to TRow click

---

changelog/13.1.0_2022-06-07/enhancement-add-nested-drop
src/components/atoms/OcDrop/OcDrop.vue

Adds "isNested" property to ocDrop that prevents the parent drop from hiding (not fires hideAll() in onShow() of child drop)
- Fixes https://github.com/owncloud/owncloud-design-system/issues/2238
Useful to create submenus
- [] Documentation added/updated

Nested drop functionality

---

changelog/unreleased/bugfix-lazy-loading-table
src/components/atoms/_OcTableCellData/_OcTableCellData.vue
src/components/molecules/OcTable/OcTable.vue
src/composables/useIsVisible/index.js
src/composables/useIsVisible/index.spec.js

Turns out that the debounce option causes significant load during
rendering, hence it's been removed.

Remove debounce from lazy loading option in OcTableCellData

---

docs/components/tokens/IconList.vue
docs/components/tokens/_HighlightedText.vue

This PR switches the icon docs page to a lazy loaded OcTable and adds a filter field.
Make the icon docs page better usable.

Switched the icon docs page to a lazy loaded OcTable and added a filter field

---

changelog/unreleased/bugfix-lazy-loading-table
docs/components/tokens/IconList.vue
src/components/atoms/_OcTableCellData/_OcTableCellData.vue
src/components/atoms/_OcTableRow/_OcTableRow.vue
src/components/molecules/OcTable/OcTable.vue

The render performance of the lazy loading option in tables (OcTable, OcTableSimple) has been improved by removing the debounce option and by moving the lazy loading visualization from the OcTd to the OcTr component. For lazy loading, the colspan property has to be provided now.
- https://github.com/owncloud/web/issues/7038

Move table lazy loading from OcTd to OcTr

---

changelog/unreleased/bugfix-oc-avatar-item-width-shrinking
src/components/atoms/OcAvatarItem/OcAvatarItem.vue

Fixes avatar width shrinking by group avatars
- Fixes https://github.com/owncloud/owncloud-design-system/issues/2241

fix: group avatars by long group names in sidebar

---

changelog/unreleased/bugfix-avatar-initials-special-chars
src/components/molecules/OcAvatar/OcAvatar.spec.js
src/components/molecules/OcAvatar/OcAvatar.vue

Omit characters from user avatar initials which don't match the unicode categories "letter" or "number".
Used unicode property escapes for this, further reading: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes
- Fixes https://github.com/owncloud/owncloud-design-system/issues/2070
Added unit tests for the function that extracts the initials. Reduced the user initials unit tests to one case, because relevant table test cases moved to the function mentioned before.

Omit special chars from avatar initials

---

changelog/unreleased/bugfix-avatar-link-icon
src/components/molecules/OcAvatarLink/OcAvatarLink.vue

- Part of https://github.com/owncloud/web/issues/7345
Before:
After:

Update the avatar link icon to the current icon used in Web

---

changelog/unreleased/enhancement-drop-offset
src/components/atoms/OcDrop/OcDrop.vue
src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap

We've added an offset property to the drop component to define a custom offset. Also, the max width of drop menus was increased to 400px.
- Part of https://github.com/owncloud/web/issues/7335

Add offset property to the drop component

---

changelog/unreleased/enhancement-breadcrumb-context-menu-alignment
src/components/molecules/OcBreadcrumb/OcBreadcrumb.vue

We've aligned the breadcrumb context menu visually to match with the regular context menu in the files table.
- Fixes https://github.com/owncloud/web/issues/7493
Old:
New:

Align breadcrumb context menu with regular context menu

---

changelog/unreleased/enhancement-use-inter
src/styles/theme/oc-text.scss

use single storey letter "a"
what does it do?  
go to https://rsms.me/inter/lab/?feat-cv11=1 and tick "cv 11 (Single-storey a)" and watch how the small letter "a" changes.
What does it improve?  
The rendering of a single storey letter a aligns with our other rounded letters and digits.

use single-storey letter a

---

changelog/unreleased/enhancement-oc-card-style
src/components/atoms/OcDrop/OcDrop.vue
src/components/atoms/OcDrop/__snapshots__/OcDrop.spec.js.snap
src/styles/theme/login.scss
src/styles/theme/oc-card.scss

The border radius of the `oc-card` class was a little bit too heavy for e.g. drop menus where it's also used. We lowered the border-radius of `oc-card` to 5px and set the border-radius only for `oc-login-card` to 15px.

fix: adjust border radius of oc-card vs oc-login-card

---

changelog/unreleased/enhancement-button-text-align-left
src/components/atoms/OcButton/OcButton.vue

We've changed the text alignment of buttons to left. We could make it configurable in the future, but for now I don't see a situation where we want to have the text centered.
- Fixes https://github.com/owncloud/web/issues/7619

Change button text alignment to left

---

changelog/unreleased/enhancement-search-cancel
src/components/atoms/OcSearchBar/OcSearchBar.vue

We've added to possibility to have a "cancel"-button and -handler in the `OcSearchBar` component.
- Needed for https://github.com/owncloud/web/issues/7617

Add cancel-button and -handler to search component

---

changelog/unreleased/enhancement-add-contextual-helper-modal
src/components/organisms/OcModal/OcModal.vue
src/components/organisms/OcModal/__snapshots__/OcModal.spec.js.snap

See https://github.com/owncloud/web/issues/6892#issuecomment-1245438400
https://github.com/owncloud/web/issues/6892
**Why new props instead of using slot:** So we can use it via code without markup

Enhancement: Give OcModal the option to use OcContextualHelper

---

changelog/unreleased/bugfix-translate-contextual-helpers
src/components/molecules/OcInfoDrop/OcInfoDrop.vue

We've fixed a bug where contextual helpers were not translated.
- Fixes https://github.com/owncloud/web/issues/7716

Fix translations for contextual helpers

---

changelog/unreleased/enhancement-input-background-color
changelog/unreleased/enhancement-select-hover-state
src/components/atoms/OcButton/OcButton.vue
src/components/atoms/OcSelect/OcSelect.vue
src/tokens/ods/color.yaml

Follow-up for https://github.com/owncloud/owncloud-design-system/pull/2345:
* Increase button padding by `.1 rem` to compensate for the removed border.
* Adjust the background color for the `OcTextInput` component as well to match with the new `OcSelect` background.

Align components with design in Figma #2

---

changelog/unreleased/enhancement-remove-button-border
src/components/atoms/OcButton/OcButton.vue

Follow-up for https://github.com/owncloud/owncloud-design-system/pull/2352. We (currently) only have passive button groups in Web, hence the outline should be passive as well.

Use passive color for button group outline
